### ISSUE TITLE
mac os lens doesn't show itself in dock

### ISSUE THREAD

**Issue by lwabish** [kontena/lens#6891] opened 2023-01-09 08:11 UTC
**Describe the bug**
After recent upgrade of lens on my macbook, I found that lens icon is not showing in dock.
Also, I can't use command+tab to quickly navigating to lens.
The only way to come back to lens is to click the icon from mac menu bar, which is much less convenient.

**To Reproduce**
1. Start lens
2. Check mac dock, most of the time, lens doesn't show itself.But sometimes lens does shows itself.

**Expected behavior**
Always show lens icon in dock.
Able to navi back to lens using command+tab

**Environment (please complete the following information):**
- Lens Version: 
>Lens: 2022.12.221341-latest
Extension API: 6.2.5
Electron: 19.1.9
Chrome: 102.0.5005.167
Node: 16.14.2
© 2022 Mirantis, Inc.
- OS: [e.g. OSX] macOS 13.1 (22C65)
- Installation method (e.g. snap or AppImage in Linux):  at first brew, many auto upgrading of lens itself after installing

**Comment by Nokel81** [comment] 2023-01-09 13:54
Duplicate of https://github.com/lensapp/lens/issues/6756, already fixed in master

**Closed as not planned by Nokel81** 2023-01-09 13:54 UTC
Labels: bug, area/macos
