### ISSUE TITLE
App crash at hpa

### ISSUE THREAD

**Issue by stephenlacy** [kontena/lens#4315] opened 2021-11-10 20:23 UTC
**Describe the bug**
Crash Error report in window when saving a HPA file.

**To Reproduce**
1. Go to 'Workloads/HPA'
2. Edit manifest
3. Save

**Environment (please complete the following information):**
- Lens Version: `5.2.6-latest.20211104.1`
- OS: macos Catalina

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Error stack:

TypeError: Cannot read property 'type' of undefined
    at hpa_api_HorizontalPodAutoscaler.getMetricValues (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:582834:35)
    at HorizontalPodAutoscalers.getTargets (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:613931:34)
    at renderTableContents (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:613962:22)
    at ItemListLayout.getRow (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:590328:13)
    at http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:576885:17
    at http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:551467:49
    at http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:551431:25
    at trackDerivedFunction (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:2024:18)
    at Reaction.track (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:2552:18)
    at useObserver (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:551429:14)
    at http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:551467:16
    at Ch (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:522232:137)
    at li (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:522255:154)
    at ki (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:522253:169)
    at ck (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:522349:157)
    at bk (http://dd20f5deb1755aedfd6310c4c3c88251.localhost:51321/build/Lens.js:522325:347)
```

It appears to be coming from here when the metrics are "set" but not actually returned: [getMetricValues](https://github.com/lensapp/lens/blob/c6dce043a7e3311af608566f60268ea1009e0609/src/common/k8s-api/endpoints/hpa.api.ts#L144)

**Comment by Nokel81** [comment] 2021-11-12 14:24
Duplicate of https://github.com/lensapp/lens/issues/4275

**Closed as completed by Nokel81** 2021-11-12 14:24 UTC
Labels: bug
