### ISSUE TITLE
There is no ability to see pod's logs

### ISSUE THREAD

**Issue by rendasaev** [kontena/lens#3839] opened 2021-09-20 09:10 UTC
**Describe the bug**
There is no button for viewing of pod's logs on pod's screen.

**To Reproduce**
1. Go to Pods
2. Click on any pod

**Expected behavior**
Should be button for viewing of pod's logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/67231406/133979124-1dc9a015-25f0-4be1-b025-9f57e9fe4a8a.png)

**Environment (please complete the following information):**
- ![image](https://user-images.githubusercontent.com/67231406/133979178-12ec6967-e882-4691-bdb0-e5c55765ccf6.png) 
- Windows 10: build 19042.1110

**Comment by Nokel81** [comment] 2021-09-20 13:36
Thanks for the bug report. This is a duplicate of https://github.com/lensapp/lens/issues/3548. and possibly related to https://github.com/lensapp/lens/issues/3482

**Closed as completed by Nokel81** 2021-09-20 13:36 UTC
Labels: bug
