### ISSUE TITLE
Suspicious behavior in kontena-lens on Ubuntu

### ISSUE THREAD

**Issue by ricardofsj** [kontena/lens#7307] opened 2023-03-07 14:50 UTC
It was identified by EDR in Ubuntu 22.04 that when starting LENS a connection is established with a web server on port 443 and "bash -l -i" is executed.
The web server is not always the same. The following addresses were identified:
- 162.159.153.4
- 147.75.40.148
- 104.244.42.1
- 104.244.42.129
- 104.244.42.193
- 54.94.183.148
- 18.230.171.141

![image](https://user-images.githubusercontent.com/57369079/223457503-ec91c9e7-17e8-4719-be02-b2ade36b2c80.png)

**Comment by Nokel81** [comment] 2023-03-07 16:16
This is correct behaviour. We are not issuing a reverse shell.

Duplicate of #6993

**Closed as completed by Nokel81** 2023-03-07 16:16 UTC
