### ISSUE TITLE
filter text box - backspace does not work when text is selected

### ISSUE THREAD

**Issue by marafa-sugarcrm** [kontena/lens#5076] opened 2022-03-22 12:53 UTC
**Describe the bug**
 using backspace key on the selected text in the filter box does not delete the text. you must click on the x button in the filter box or unselect the text and use the backspace key to delete character by character

**To Reproduce**
1. Go to any screen that has a text box to filter . eg. pods secrets anything.
2. write down any text
3. select the text
4. press back space key

**Expected behavior**
backspace on selected text will delete that text

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.4.3
- OS: [e.g. OSX]  osx 12.3
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment] 2022-03-28 12:49
Can you please provide a short recording of this behaviour as we cannot reproduce from your description.

**Comment by Nokel81** [comment] 2022-06-15 16:00
I think this is a duplicate of #5588

**Closed as completed** 2022-06-30 12:26 UTC
Labels: bug, area/ui
