### ISSUE TITLE
v6.3.0 can't view pod logs

### ISSUE THREAD

**Issue by szinn** [kontena/lens#6811] opened 2022-12-21 20:48 UTC
**Describe the bug**
The menu option to view logs for a pod is not available. It was in the previous version

Also refresh (cmd-R) from pods tab loses the namespace selections and reverts back to all namespaces.

**To Reproduce**
1. Goto to pods tab
2. click on the ... and logs is missing

**Expected behavior**
logs should be availavble

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 6.3.0
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Firehed** [comment] 2022-12-21 23:05
I've also lost the pod shells in 6.3.0, in addition to logs. Rolling back to 6.2.5 resolved both.

**Comment by szinn** [comment] 2022-12-21 23:36
How did you roll back?

**Comment by ogarcia** [comment] 2022-12-23 09:16
It seems to be intentional. See this comment:
https://github.com/lensapp/lens/issues/6819#issuecomment-1363751421

**Comment by msa0311** [comment] 2022-12-23 09:34
duplicate of #6823

**Closed as completed by msa0311** 2022-12-23 09:34 UTC
Labels: bug

**Comment by sigmonsays** [comment] 2022-12-27 19:05
I'd have a lot more respect for you if you admitted you'd taken the decision to take core functionality closed source for commerical reasons.
