### ISSUE TITLE
Ingress objects not showing up

### ISSUE THREAD

**Issue by VishDev12** [kontena/lens#4443] opened 2021-11-27 16:00 UTC
**Describe the bug**
No ingress objects are visible for any namespace selected. The yellow triangle that shows up next to the namespace dropdown shows an "undefined" tooltip when hovering over it. `kubectl get ingress -n default` from the terminal works as expected, so it doesn't seem to be a permissions issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/19661538/143688242-f82daad7-f0c4-483c-8867-efd49190f939.png)

**Environment (please complete the following information):**
- Lens Version: 5.3.0-latest.20211125.2
- OS: Windows 10
- Installation method: Windows x64 (.exe)

**Comment by EdwinPhilip** [comment] 2021-11-29 13:04
I can confirm this happens in my Mac too with same `5.3.0-latest.20211125.2`

**Comment by SergeSpinoza** [comment] 2021-11-30 08:10
Hi. Have the same issue on Macos Catalina, Lens: 5.3.0-latest.20211125.2

**Comment by hydramyst** [comment] 2021-11-30 08:16
hello, macOS Monterey, Lens: 5.3.0-latest.20211125.2 have a same problem.

**Comment by justabaka** [comment] 2021-11-30 11:11
That's probably due to some changes in API support that turned out to be not backwards compatible. I can see Ingress objects in k8s v1.22.4 clusters but not in v1.16.11. I doubt it's platform-dependent as I'm running Lens on Linux

**Comment by Nokel81** [comment] 2021-11-30 14:09
> That's probably due to some changes in API support that turned out to be not backwards compatible. I can see Ingress objects in k8s v1.22.4 clusters but not in v1.16.11. I doubt it's platform-dependent as I'm running Lens on Linux

Yes, there is a bug in our fallback logic for the ingress API (because it was moved from `/apis/extensions/v1beta1/ingresses` to its current location).

I am pretty sure that this bug is a lot older than 3 days old.

**Comment by Moskovych** [comment] 2021-11-30 15:46
Is this issue are going to be fixed asap? Can't use Lens with older clusters.

**Comment by Nokel81** [comment] 2021-11-30 15:47
@Moskovych Yes, the PR is up today and we plan on releasing a patch release once it is merged

**Comment by Moskovych** [comment] 2021-11-30 15:52
@Nokel81 , btw, it there any documentation about Lens compatibility of K8s versions?

**Comment by Nokel81** [comment] 2021-11-30 15:56
@Moskovych There is not. We currently have a fixed apiBase for all the resources we query (except ingresses which we have this fallback). But because the kube api does conversions between resource apiVersions it should work as long as your kube supports those versions.

**Closed as completed** 2021-11-30 16:27 UTC
Labels: bug
