### ISSUE TITLE
Feedback after "Check for updates"

### ISSUE THREAD

**Issue by clrothmann** [kontena/lens#6141] opened 2022-08-30 14:44 UTC
**What would you like to be added**:

After using "Check for updates" I want to be informed if my version is up to date.
Currently I don't get any response

**Why is this needed**:

To ensure working on the latest version

E.g. a pop-up with a message "You're all good. You've got the latest version of Lens Desktop; thanks for staying on the ball."

**Comment by Nokel81** [comment] 2023-03-28 13:24
Closed as duplicate of #7228

**Closed as not planned by Nokel81** 2023-03-28 13:24 UTC
Labels: enhancement, area/auto-update, p2
