### ISSUE TITLE
lens black taskbar icon almost not visible in dark mode on windows 10

### ISSUE THREAD

**Issue by luckyluc74** [kontena/lens#5742] opened 2022-06-27 15:09 UTC
This is how lens icon looks like in windows 10 dark mode
![image](https://user-images.githubusercontent.com/6342858/175888101-651be68c-3ca4-4077-acff-a19640914ce6.png)

Would be nice if icon would be better visible in dark mode :)

**Comment by Nokel81** [comment] 2022-06-27 20:01
Duplicate of #5713. This has been fixed for 5.6

**Closed as not planned by Nokel81** 2022-06-27 20:01 UTC
Labels: bug
