### ISSUE TITLE
Cannot open a pop-up menu + a cluster display problem

### ISSUE THREAD

**Issue by dzhigzhitzhapov** [kontena/lens#5388] opened 2022-05-13 08:26 UTC
**Describe the bug**
This problem has been found when using Lens Desktop for Windows.

**Steps to reproduce:**

1. Open Lens
2. Navigate to a local cluster
3. Click the icon with initial letters of your name (personal actions pop-up menu)

**Wrong behaviour:**

The application displays the error report. After clicking **Back**, a user cannot enter the cluster. The app displays blank space.

*Component stack:*

```
 at t (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:1438:42338)
    at C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:360:3889
    at wi (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:158:128959)
    at div
    at C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:158:125011
    at C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:158:131416
    at C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:1213:1287
    at C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:1:4556
    at Ym (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:1232:247)
    at Qm (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:1246:854)
    at div
    at C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:21:115402
    at c (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:158:101988)
    at div
    at div
    at observerComponent (http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:266183:16)
    at div
    at NonInjectedClusterManager (http://localhost:55796/build/chunks/8185.js:1216:33)
    at ErrorBoundary (http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:581925:9)
    at RootFrame (http://localhost:55796/build/chunks/8185.js:1300:9)
    at ThemeProvider (http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:127160:24)
    at Router (http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:454619:30)
```

*Error stack:*

```
TypeError: Cannot set properties of undefined (setting 'getCurrentStack')
    at je (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:90:11579)
    at C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:103:174485
    at Object.t.findDOMNode (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:103:174511)
    at t.n.performEnter (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:1438:43615)
    at t.n.updateStatus (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:1438:43358)
    at t.n.componentDidMount (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:1438:42761)
    at ak (http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:453194:219)
    at Yj (http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:453193:450)
    at Xj (http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:453192:148)
    at Mk (http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:453216:81)
    at Fk (http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:453214:396)
    at uk (http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:453206:439)
    at dg (http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:453061:105)
    at http://localhost:55796/build/Lens.js?3625b34cb611d08a0238:453201:269
```

**Expected behaviour:**

The actions pop-up menu appears in the upper-right corner of the app.

**Comment by Nokel81** [comment] 2022-05-13 18:34
What version are you running? Are you running `v5.5.0-beta.0` because if so then the solution would be to upgrade to `v5.5.0-beta.1` once it is released.

**Comment by dzhigzhitzhapov** [comment] 2022-05-16 08:24
Got it, thanks!

**Comment by Nokel81** [comment] 2022-05-16 13:11
This is also a duplicate of the second item posted in https://github.com/lensapp/lens/issues/5336

**Closed as completed by Nokel81** 2022-05-16 13:11 UTC
Labels: bug
