### ISSUE TITLE
Horizontal Pod Autoscalers - CPU Metrics - Showing the wrong values. 

### ISSUE THREAD

**Issue by mmoses** [kontena/lens#5951] opened 2022-07-29 08:11 UTC
**Describe the bug**
CPU metrics in the HPA is showing the max cpu instead of the current cpu.

kubectl hpa XXXX    ->   Deployment/       70%/85%  

vs - the 85%/85% in lens - see [screenshot]([url]([url](url))) 
<img width="746" alt="Screen Shot 2022-07-29 at 10 59 14" src="https://user-images.githubusercontent.com/395566/181714583-1080132e-d59a-49f8-bfe1-c1eb664114a9.png">

<img width="1170" alt="hpa" src="https://user-images.githubusercontent.com/395566/181714642-d2287f4b-75b9-497e-a4e7-cb8942b7cb7c.png">

**Comment by armujahid** [comment] 2022-07-29 10:10
Lens 6 is showing current = target for all HPAs. This issue wasn't observed in Lens 5
![image](https://user-images.githubusercontent.com/3725386/181737159-2290a1ba-6b96-45a9-9a4f-2806c25cf91a.png)

**Comment by armujahid** [comment] 2022-07-29 10:13
Duplicate of https://github.com/lensapp/lens/issues/5942

**Comment by Nokel81** [comment] 2022-07-29 13:31
Closing as duplicate

**Closed as not planned by Nokel81** 2022-07-29 13:31 UTC
Labels: bug
