### ISSUE TITLE
sticky filters/search

### ISSUE THREAD

**Issue by MarcMielke** [kontena/lens#4281] opened 2021-11-08 10:58 UTC
It would be great to have the option to use `sticky` filters/search value entries. Such that when one filters for `label=value` the search field does not get reset when switching `kind`s.

**Comment by Nokel81** [comment] 2021-11-08 13:53
Duplicate of https://github.com/lensapp/lens/issues/3510

**Closed as completed by Nokel81** 2021-11-08 13:53 UTC
Labels: enhancement

**Comment by MarcMielke** [comment] 2021-11-08 14:32
thx, didn't see that.
