### ISSUE TITLE
Export https_proxy variable before trying to open pod shell

### ISSUE THREAD

**Issue by Tri0L** [kontena/lens#4446] opened 2021-11-29 02:14 UTC
I have k8s cluster with proxy before kubernetes api.
I have set http proxy in settings.
I can connect to cluster and work with it.

But if I want to run pod shell, I have a problem that lens not export https_proxy variable before run command to connect to pod shell.

Settings:
<img width="779" alt="Снимок экрана 2021-11-29 в 05 13 30" src="https://user-images.githubusercontent.com/1208486/143798341-5904f008-8ed1-472a-9309-fddbb3dc83e3.png">

Lens run this command:
`exec kubectl exec -i -t -n default mypod -c mypod -- sh -c "clear; (bash || ash || sh)"`

I think, if proxy variable set in settings, it would be right to run command like this:
`https_proxy=10.10.0.1:8118 exec kubectl exec -i -t -n default mypod -c mypod -- sh -c "clear; (bash || ash || sh)"`

where `10.10.0.1:8118` is value of proxy address from settings.

**Comment by Nokel81** [comment] 2021-11-29 13:59
Duplicate of https://github.com/lensapp/lens/issues/2021

**Closed as completed by Nokel81** 2021-11-29 13:59 UTC
Labels: enhancement
