### ISSUE TITLE
Blank cluster screen when running a build from source (6.3)

### ISSUE THREAD

**Issue by joshualex** [kontena/lens#6829] opened 2022-12-26 09:26 UTC
I'm trying to build an run the source locally (running on macOS Ventura 13.1) - and I used the official v.6.3.0 release archive. 
Building via `make build` works flawlessly, but when I try to go to one of my cluster configs - the main pane comes out blank. The developer tools don't show any console errors or suspicious logs. Any idea why this could be?

**Comment by aleksfront** [comment] 2022-12-26 12:30
Hi @joshualex! I can't reproduce it locally. Can you provide any kind of extra information on this? What type of clusters do you have?

Can you please start an app from the terminal and see logs there?

**Comment by alebcay** [comment] 2022-12-27 03:02
Might be related: https://github.com/MuhammedKalkan/OpenLens/issues/81.

**Comment by jansav** [comment] 2022-12-27 07:27
Could you verify if developer tools shows any failed network calls? We managed to reproduce this by blocking network calls to `OpenLens.js` and now we are thinking if this is something that you might encounter. 

<img width="623" alt="image" src="https://user-images.githubusercontent.com/3083083/209628458-1acff908-859c-4fef-a7e1-ffdffeaee6ac.png">

**Comment by jansav** [comment] 2022-12-27 08:58
Update: Hypothesis over network failure is overruled with new hypothesis for race-condition during application start. #6690 removes a lot from application start so maybe it also introduces race-condition that causes this. 

At least the behaviour is exactly same when there's non resolving promise in `initClusterFrame`.

@joshualex could you test against latest version from master? I'd like to double check that this hasn't been fixed already.

FYI @Nokel81

**Comment by jansav** [comment] 2022-12-27 12:54
Update: Found out the issue and resolving it with a top priority. More details when issue has been resolved.

**Closed as completed** 2022-12-28 06:19 UTC
Labels: bug, p0

**Comment by joshualex** [comment] 2022-12-29 13:27
Thanks! Will test it out and report back

**Comment by joshualex** [comment] 2022-12-29 17:13
@jansav Seems to work fine off of master. Thanks!
