### ISSUE TITLE
Upgrading helm release leads to crash

### ISSUE THREAD

**Issue by jansav** [kontena/lens#5852] opened 2022-07-19 11:55 UTC
**Describe the bug**

`cannot reload values if no data` 

**To Reproduce**
1. Go to Helm Releases
2. Choose to upgrade release
3. Close tab

----
1. Go to Helm Releases
2. Choose to upgrade release
3. Refresh page when tab is open

**Screenshots**

https://user-images.githubusercontent.com/3083083/179744125-1f2d34a9-d126-400e-9900-9eafb056bced.mov

https://user-images.githubusercontent.com/3083083/179744148-c3a12eb8-7a90-49f4-98ac-c1145f9abbde.mov

**Environment (please complete the following information):**
- Lens Version: 5.6.0-alpha.6.2
- OS: OSX

**Comment by Nokel81** [comment] 2022-08-11 12:43
Duplicate of https://github.com/lensapp/lens/issues/5678

**Closed as not planned by Nokel81** 2022-08-11 12:43 UTC
Labels: bug, p1
