### ISSUE TITLE
No UI in certain Clusters

### ISSUE THREAD

**Issue by turowicz** [kontena/lens#4684] opened 2022-01-13 15:29 UTC
**Describe the bug**
I have one of the clusters that I don't get a UI for after connecting to it:

![image](https://user-images.githubusercontent.com/1055391/149359013-aeda3929-71a9-4211-a0a7-d702d3460cdf.png)

**To Reproduce**
Nobody can reproduce this 

**Expected behavior**
The UI should load.

**Screenshots**
At the top.

**Environment (please complete the following information):**
![image](https://user-images.githubusercontent.com/1055391/149359150-f5fa0da9-b21b-48a6-b794-e6849e779bbb.png)
Installed via deb on Ubuntu 21.10

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
N/A - It works for other team members with older Lens (5.0.x)

**Comment by Nokel81** [comment] 2022-01-13 15:45
Duplicate of https://github.com/lensapp/lens/issues/4018

**Closed as completed by Nokel81** 2022-01-13 15:45 UTC
Labels: bug
