### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by guzzd** [kontena/lens#5485] opened 2022-05-27 15:39 UTC
**Describe the bug**
No connection

**To Reproduce**
1. Open application

**Expected behavior**
Application will open

**Screenshots**

![image](https://user-images.githubusercontent.com/19326377/170732432-6f0e0cba-1b8a-4e47-9f73-96dd3158f05e.png)

**Environment (please complete the following information):**
- Lens Version: don't know since I can't pass that window
- OS: W11
- Installation method (e.g. snap or AppImage in Linux): from web (standard)

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
All other tools I work with kubernetes works as a charm!

**Comment by Nokel81** [comment] 2022-05-30 13:16
Duplicate of https://github.com/lensapp/lens/issues/5482

**Closed as not planned by Nokel81** 2022-05-30 13:16 UTC
Labels: bug
