### ISSUE TITLE
Lens Prometheus installation doesn't work on Vultr

### ISSUE THREAD

**Issue by collimarco** [kontena/lens#6491] opened 2022-10-31 15:45 UTC
Trying to install Prometheus on a Vultr K8s cluster using Lens -> Settings -> Lens Metrics -> Enable bundled Prometheus.

I get this error:

```
failed to provision volume with StorageClass "vultr-block-storage-hdd": rpc error: code = Internal desc = {"error":"Unable to add block storage: Failed to add block storage device. Invalid size (20GB) - Must be between 40GB and 40000GB.","status":400}
```

I don't see any option to change the volume size, so this is a bug that prevents the installation.

Can you fix this? Any workaround?

**Comment by Nokel81** [comment] 2022-10-31 18:56
Duplicate of https://github.com/lensapp/lens/issues/5398

**Closed as not planned by Nokel81** 2022-10-31 18:56 UTC
Labels: bug
