### ISSUE TITLE
Lens deleting entire statefulset instead a single selected pod

### ISSUE THREAD

**Issue by epicvinny** [kontena/lens#5494] opened 2022-05-28 22:10 UTC
**Describe the bug**
When you try to delete a specific pod in a statefulset, lens delete the entire statefulset.

**To Reproduce**
1. Go to Workloads > Statefulsets
2. Click on a specific statefulset
3. Scroll down to Pods and click in a specific pod
4. Click on delete button anc click in remove.

**Expected behavior**
Instead of delete the entire statefulset, delete only the selected pod.

**Environment (please complete the following information):**
- Lens Version: 5.5.1-latest.20220526.1
- OS: Windows 11

**Comment by Nokel81** [comment] 2022-05-30 13:25
Probably duplicate of https://github.com/lensapp/lens/issues/5492

**Closed as not planned by Nokel81** 2022-05-30 13:25 UTC
Labels: bug
