### ISSUE TITLE
[Bug]Blank panel after connecting to cluster

### ISSUE THREAD

**Issue by johnphilipscs** [kontena/lens#4303] opened 2021-11-09 18:31 UTC
When starting Lens and connecting to a cluster that was previously connected, the connection is established but the main panel is blank.  This appears to be related to #1039.  Having this issue regularly on laptop but not on desktop.  Given discussion in #1039 may be related to network becoming disconnected as laptop is put to sleep on a regular basis.  Also, this is on MacOS 11.6 and Lens 5.2.6-latest.20211104.1.

Note the fix I have is to delete the setting folder at ~/Library/Application Support/Lens and then the panel appears.

**Comment by Nokel81** [comment] 2021-11-09 18:39
Duplicate of #4018

**Closed as completed by Nokel81** 2021-11-09 18:39 UTC
