### ISSUE TITLE
App crash at /workloads [Lens-5.2.4-latest.20210923.1.amd64] on Ubuntu 21.04

### ISSUE THREAD

**Issue by funnyguygithub** [kontena/lens#3895] opened 2021-09-25 07:34 UTC
**App crash at /workloads**

**To Reproduce**
1. Go to 'Workloads'
2. Click on 'Overview'
3. It loads metrics, starting displaying, but then crashes 

Error stack:

`TypeError: Cannot read property 'clientWidth' of undefined
    at render (~/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:608021)
    at allowStateChanges (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:1472:12)
    at http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:10151:59
    at trackDerivedFunction (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:2024:18)
    at Reaction.track (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:2552:18)
    at reactiveRender [as render] (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:10149:14)
    at qi (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535639:188)
    at pi (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535638:173)
    at ck (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535721:427)
    at bk (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535702:347)
    at ak (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535702:278)
    at Tj (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535702:138)
    at Lj (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535695:163)
    at http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535575:115
    at exports.unstable_runWithPriority (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535786:343)
    at gg (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535574:325)
    at jg (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535575:61)
    at ig (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535574:428)
    at Jg (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535689:203)
    at Object.enqueueSetState (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:535585:211)
    at r.C.setState (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:459170:369)
    at r.generateChartDataSeries (/home/funnyguy/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:597517)
    at r.displayChart (~/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:597140)
    at r.componentDidMount (~/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:597935)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`
 

Component stack:

`
    at r (~/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:595820)
    at div
    at div
    at Details
    at div
    at WorkloadsOverview (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:607438:34)
    at Route (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:32471:29)
    at Switch (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:32641:29)
    at ErrorBoundary (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:572072:47)
    at ErrorBoundary (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:572181:36)
    at main
    at div
    at http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:9707:16
    at Workloads (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:610679:41)
    at Route (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:32471:29)
    at Switch (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:32641:29)
    at ErrorBoundary (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:572072:47)
    at ErrorBoundary (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:572181:36)
    at div
    at div
    at MainLayout (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:572611:9)
    at ErrorBoundary (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:572072:47)
    at ErrorBoundary (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:572181:36)
    at Router (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:32134:30)
    at App (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:666352:9)
    at ThemeProvider (http://ef9454edd80796e0267cfab8a895bb1a.localhost:38363/build/Lens.js:700028:24)`

**Expected behavior**
Display the Workload Overview

**Screenshots**

![image](https://user-images.githubusercontent.com/49163158/134762945-6dc50aa6-5938-4775-8f30-1f04d47f957d.png)

**Environment (please complete the following information):**
- Lens Version:  Lens-5.2.4-latest.20210923.1
- OS: [e.g. OSX]  Ubuntu 21.04 x86_64 
- Installation method (e.g. snap or AppImage in Linux):  Lens-5.2.4-latest.20210923.1.amd64.deb

**Additional context**
1. It works on Mac fine. 
2. Lens-4.2.5  works fine - no issues with Workloads - Overview on the same Ubuntu laptop.

**Comment by systemmonkey42** [comment] 2021-09-27 07:58
Please search for issues before posting.

Duplicate of #3889  #3861 #3835  #3830   and probably others.   The solution is at the end of each.

https://github.com/lensapp/lens/issues/3835#issuecomment-922673793

**Closed as completed** 2021-09-27 13:17 UTC
Labels: bug
