### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by kelvinbg** [kontena/lens#5489] opened 2022-05-27 22:31 UTC
I am facing this error after upgrading Len to the latest version. Before Version was working with issues. And I would like to revert back to that if possible.
<img width="953" alt="noconnection-lens" src="https://user-images.githubusercontent.com/98049461/170796668-03259bb5-46bf-4bb2-bf68-2c9f4a5e9886.PNG">

**Comment by StevDa86** [comment] 2022-05-30 06:22
Same Problem here. Please Fix!  :(

**Comment by Mo7amed178** [comment] 2022-05-30 06:57
@StevDa86 @kelvinbg 
I was facing this issue this moening , just downgrading to 5.1.3 version , and its working now

**Comment by Nokel81** [comment] 2022-05-30 13:17
Duplicate of https://github.com/lensapp/lens/issues/5482

**Closed as not planned by Nokel81** 2022-05-30 13:17 UTC
