### ISSUE TITLE
is it possible to auto wrap the log view

### ISSUE THREAD

**Issue by jiangxiaoqiang** [kontena/lens#4399] opened 2021-11-20 02:31 UTC
I am using the 5.2.7 version of lens but I did not found where to setting the log autowrap. If the log is too long, read it is a hard work by drag the bar. Could you please add a autowarp about the pod log view of Lens?

**Comment by Nokel81** [comment] 2021-11-22 14:25
Duplicate of https://github.com/lensapp/lens/issues/1077

**Closed as completed by Nokel81** 2021-11-22 14:25 UTC
Labels: enhancement, area/logs
