### ISSUE TITLE
Can't read/view CRD in lens

### ISSUE THREAD

**Issue by csantanapr** [kontena/lens#4249] opened 2021-11-03 22:32 UTC
Can't read/view CRD in lens
Hi @Nokel81 I don't see the "Edit" on this screenshot.
I repeat I want to edit the CRD and not the CR
![image](https://user-images.githubusercontent.com/1094878/140207113-d38f7cb0-100c-4a73-8ada-ced8ad07076a.png)
This is the yaml I want to view, it can't be edited but it should be able to read it.
Like
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
  creationTimestamp: "2021-10-27T16:21:48Z"
  generation: 1
  labels:
    app.kubernetes.io/part-of: knative-operator
    app.kubernetes.io/version: 20211027-f28261ba
    operator.knative.dev/release: v20211027-f28261ba
  name: knativeservings.operator.knative.dev
  resourceVersion: "1878115"
  uid: 459d5f1f-ef22-4986-9e7e-6dbf403fb900
spec:
  conversion:
    strategy: None
  group: operator.knative.dev
```

**Comment by csantanapr** [comment] 2021-11-03 22:33
should be the same as
```
kubectl explain knativeservings
```

**Comment by Nokel81** [comment] 2021-11-04 12:46
Closing as duplicate of https://github.com/lensapp/lens/issues/4180

I posted some screenshots in that issue which show where you can view the CRD data itself

**Closed as completed by Nokel81** 2021-11-04 12:46 UTC
Labels: bug
