### ISSUE TITLE
more shortcut key with mnemonics

### ISSUE THREAD

**Issue by faisal6621** [kontena/lens#6786] opened 2022-12-19 17:28 UTC
**What would you like to be added**:
Currently there are limited number of shortcut keys with mnemonic available. e.g., for closing the logs window pressing `Ctrl+W`. Similarly there must be some mnemonic for **maximize**, **restore** and **minimize** the tools (logs, config editor) window.

**Why is this needed**:
To be more productive with keyboard shortcuts instead of moving around the cursor.

**Environment you are Lens application on:**

- Desktop OS: Windows, MacOS

**Comment by matti** [comment] 2022-12-20 08:22
@faisal6621 yes - can you rename the issue to be without a typo.

same applies for mac - we need shortcuts!

**Comment by Nokel81** [comment] 2023-01-03 14:01
Duplicate of #177 and others. This is indeed a very good idea. Will work on getting this a prioritisation.

**Closed as not planned by Nokel81** 2023-01-03 14:01 UTC
Labels: enhancement
