### ISSUE TITLE
Are there any plans to support Chinese?

### ISSUE THREAD

**Issue by joesdu** [kontena/lens#4917] opened 2022-02-22 13:47 UTC
**What would you like to be added**:

**Why is this needed**:

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

**Comment by Nokel81** [comment] 2022-02-28 14:01
Duplicate of https://github.com/lensapp/lens/issues/3151, please upvote the other ticket.

**Closed as completed by Nokel81** 2022-02-28 14:01 UTC
Labels: enhancement
