### ISSUE TITLE
Cannot connect to clusters after updating to 5.5.0 (Invalid credentials)

### ISSUE THREAD

**Issue by alanbchristie** [kontena/lens#5460] opened 2022-05-26 11:00 UTC
**Describe the bug**
Could connect to the cluster with lens prior to `5.5.0` but now I'm greeted with "Invalid credentials" and cannot connect/

**To Reproduce**
Upgrade to 5.5.0 from an earlier release

**Expected behavior**
Connect to cluster with perfectly valid kubeconfig file!

**Screenshots**
<img width="362" alt="Screenshot 2022-05-26 at 11 57 51" src="https://user-images.githubusercontent.com/29806285/170475163-d8dbad25-2c8c-4127-913f-c7ea807a34d3.png">

**Environment (please complete the following information):**
- Lens Version: 5.5.0-latest.20220525.1
- OS: macOS
- Installation method (e.g. snap or AppImage in Linux): Auto update

**Logs:**
```
No time to do this yet!
```

**Kubeconfig:**
On-prem config (cannot share it)

**Additional context**
n/a

**Comment by AfonsoNeto** [comment] 2022-05-26 11:47
Same issue here

**Environment:**
- Lens Version: 5.5.0-latest.20220525.1
- OS: Windows 10
- Installation method: Auto update

**Comment by Nokel81** [comment] 2022-05-26 12:54
What sort of clusters are you trying to connect to? I have tried the following and cannot seem to reproduce.

- local minikube
- local docker desktop
- lens spaces shared cluster
- AWS cluster authenicated via `aws eks update-kubeconfig`

**Comment by tompatib** [comment] 2022-05-26 13:22
Same here after upgrading from 5.4.6. We were already suspecting this as a fresh install couldn't connect, so to verify we have connected from 5.4.6, then do the update to 5.5.x latest and cannot connect anymore.

- Rancher managed on-prem cluster throws Invalid credentials
- on-prem OpenShift gets connected but nothing loads up (blank screen).

**Comment by AfonsoNeto** [comment] 2022-05-26 13:24
Seems like a duplicate of https://github.com/lensapp/lens/issues/5455

**Comment by Nokel81** [comment] 2022-05-26 13:25
@AfonsoNeto Yes probably, will close this in favour of just reporting on that one.

**Closed as not planned by Nokel81** 2022-05-26 13:25 UTC
Labels: bug
