### ISSUE TITLE
delete a job doesnt always update

### ISSUE THREAD

**Issue by marafa-sugarcrm** [kontena/lens#5225] opened 2022-04-08 21:03 UTC
**Describe the bug**
i deleted a job with kubectl when i looked in lens. it was still there.
when i tried to delete it , i got this message
![Screen Shot 2022-04-08 at 5 01 44 PM](https://user-images.githubusercontent.com/69474017/162529449-91522e24-85f9-4e5c-a6f0-bbf7d40b70cc.png)

multiple efforts to delete the job thru lens failed.  checking with kubectl confirmed there were no jobs in this namespace. 
10 minutes has passed already

**Comment by Nokel81** [comment] 2022-04-11 12:51
Duplicate of #3821

**Closed as completed by Nokel81** 2022-04-11 12:51 UTC
Labels: bug
