### ISSUE TITLE
"TypeError: Cannot read property 'type' of undefined" in HPA page after Edit and Save HPA yaml ()

### ISSUE THREAD

**Issue by borjita** [kontena/lens#4434] opened 2021-11-26 10:03 UTC
**Describe the bug**
When an item is edited from the HPA page list and the changes are saved, the HPA page "breaks" when listing the items again.

**To Reproduce**
1. Go to 'Configuration -> HPA'
2. Click on 'any item of list', and push in "edit" button. Then edit yaml and push "save"
3. See error

**Expected behavior**
After editing and saving the changes, the item list is displayed correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/3070483/143562350-687d875b-24a5-4752-8923-e652f852aa83.png)
![image](https://user-images.githubusercontent.com/3070483/143562475-b82a2426-700b-496d-9333-906570185efb.png)
![image](https://user-images.githubusercontent.com/3070483/143562532-965e2f88-eebc-4690-8611-8da29204b165.png)
![image](https://user-images.githubusercontent.com/3070483/143562611-311231fe-2b1a-4d3c-9add-89f26c467d39.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.7-latest-20211110.1
- OS: Windows 10 PRO
- Installation method: .EXE

**Logs:**

```Component stack:


    at http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:521862:16
    at div
    at div
    at List (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:545723:30)
    at div
    at AutoSizer (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:547025:5)
    at div
    at virtual_list_VirtualList (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:547200:9)
    at div
    at Table (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:547394:9)
    at div
    at div
    at ItemListLayout (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:560623:9)
    at KubeObjectListLayout (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:561099:9)
    at HorizontalPodAutoscalers (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:584314:36)
    at Route (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:28658:29)
    at Switch (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:28828:29)
    at ErrorBoundary (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:533091:9)
    at main
    at div
    at http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:521862:16
    at Config (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:584770:32)
    at Route (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:28658:29)
    at Switch (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:28828:29)
    at ErrorBoundary (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:533091:9)
    at div
    at div
    at MainLayout (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:533537:9)
    at ErrorBoundary (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:533091:9)
    at Router (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:28321:30)
    at App (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:629856:9)
    at ThemeProvider (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:663320:24)


Error stack:

TypeError: Cannot read property 'type' of undefined
    at hpa_api_HorizontalPodAutoscaler.getMetricValues (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:553229:35)
    at HorizontalPodAutoscalers.getTargets (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:584321:34)
    at renderTableContents (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:584352:22)
    at ItemListLayout.getRow (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:560723:13)
    at http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:547280:17
    at http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:521862:49
    at http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:521826:25
    at trackDerivedFunction (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:2024:18)
    at Reaction.track (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:2552:18)
    at useObserver (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:521824:14)
    at http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:521862:16
    at Ch (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:496945:137)
    at li (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:496968:154)
    at ki (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:496966:169)
    at ck (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:497062:157)
    at bk (http://041e32c81fba87ef4ed932664a9d98cb.localhost:56913/build/Lens.js:497038:347)

**Comment by Nokel81** [comment] 2021-11-26 14:22
Duplicate of https://github.com/lensapp/lens/issues/4315 fixed in 5.3.0

**Closed as completed by Nokel81** 2021-11-26 14:22 UTC
Labels: bug
