### ISSUE TITLE
Trying to access K8 cluster but Lens doesnt shows clusters

### ISSUE THREAD

**Issue by mandarpimplapure** [kontena/lens#6641] opened 2022-11-24 13:43 UTC
Hello All,

Just downloaded Lens with Version from 21st Nov 2022 and trying to access cluster ( both PROD and Non-PROD ) 

When I am trying to insert config it gives popup message like Cluster added successfully but unable to view them under tab.  

![image](https://user-images.githubusercontent.com/16802910/203798414-8c7bf411-a463-4ff8-b983-995f873fbedd.png)

![image](https://user-images.githubusercontent.com/16802910/203798935-bfcd7051-b299-42d4-b7b9-3397dedf7d3d.png)

**Comment by Nokel81** [comment] 2022-11-28 14:01
Would you be able to provide logs from `%AppData%/Lens/Logs`?

Does restarting lens (including quitting from the tray menu) fix this issue?

**Comment by BarbaraBiskupek** [comment] 2022-12-21 09:03
Hi, I have the similar issue - after adding kubeconfig file there is message: Selected items has been added to Kubeconfig Sync.
However the list of clusters is still empty. 

![image](https://user-images.githubusercontent.com/103244623/208861994-523ade34-16a9-4aca-9aa3-d94696e60553.png)

![image](https://user-images.githubusercontent.com/103244623/208863821-df841994-2ed6-4c37-bea0-351f0c3d72f8.png)

**Comment by EvertonSA** [comment] 2023-01-18 12:23
the only solution I found for this is complete reinstall. could not find another solution.

**Comment by Nokel81** [comment] 2023-01-18 19:56
Sounds like a duplicate of #6837 which has been fixed and will be released as part of the next release.

**Closed as completed by Nokel81** 2023-01-18 19:56 UTC
Labels: bug
