### ISSUE TITLE
App crash upon Switching to Overview Tab

### ISSUE THREAD

**Issue by ludenus** [kontena/lens#4311] opened 2021-11-10 09:12 UTC
**Describe the bug**
Overview Tab renders errors with stacktarace text

**To Reproduce**
1. Go to Overview Tab

**Expected behavior**
Overview Tab should be rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/4931317/141084121-2ca1005e-511a-43ae-8e03-62036a9f562f.png)

**Environment (please complete the following information):**
- Lens Version:
Lens: 5.2.6-latest.20211104.1
Electron: 12.2.1
Chrome: 89.0.4389.128
Node: 14.16.0
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): dmg + recent update

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Component stack:


    at r (/Users/qa/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:595820)
    at div
    at div
    at Details
    at div
    at WorkloadsOverview (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:600436:34)
    at Route (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:28658:29)
    at Switch (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:28828:29)
    at ErrorBoundary (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:562696:9)
    at main
    at div
    at http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:551467:16
    at Workloads (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:603710:41)
    at Route (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:28658:29)
    at Switch (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:28828:29)
    at ErrorBoundary (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:562696:9)
    at div
    at div
    at MainLayout (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:563142:9)
    at ErrorBoundary (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:562696:9)
    at Router (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:28321:30)
    at App (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:659466:9)
    at ThemeProvider (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:692868:24)
    
    Error stack:

TypeError: Cannot read property 'clientWidth' of undefined
    at render (/Users/qa/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:608021)
    at allowStateChanges (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:1472:12)
    at http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:551911:59
    at trackDerivedFunction (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:2024:18)
    at Reaction.track (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:2552:18)
    at reactiveRender [as render] (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:551909:14)
    at r.makeComponentReactive (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:551924:25)
    at r.target.render (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:551837:34)
    at qi (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:522262:188)
    at pi (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:522261:173)
    at ck (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:522344:427)
    at bk (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:522325:347)
    at ak (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:522325:278)
    at Tj (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:522325:138)
    at Lj (http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:522318:163)
    at http://24913ff0652d4598cd99c09538f19460.localhost:50176/build/Lens.js:522198:115
    ```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
.
```

**Additional context**

**Comment by Nokel81** [comment] 2021-11-10 14:07
Duplicate of #3830 

Please upgrade your extension

**Closed as completed by Nokel81** 2021-11-10 14:07 UTC
Labels: bug
