### ISSUE TITLE
Type Error: Only absolute URLs are supported

### ISSUE THREAD

**Issue by gaow1423** [kontena/lens#3837] opened 2021-09-20 06:04 UTC
**Describe the bug**
After upgrading to 5.2X, the api call from the extension failed with above errors. it works fine before 5.2X.

**Screenshots**
![image](https://user-images.githubusercontent.com/25094170/133828297-85e9ca17-ac4f-4e5f-9c5e-efc27917bddc.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.2
- OS: macOS Big Sur version 11.6

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
TypeError: Only absolute URLs are supported
at/Applications/Lens.a.../build/preload.js:1
at/Applications/Lens.a.../build/preload.js:1
```

**Comment by jakolehm** [comment] 2021-09-20 06:44
Duplicate of #3831

**Closed as completed by jakolehm** 2021-09-20 06:44 UTC
Labels: bug
