### ISSUE TITLE
lens becomes unusable with 15,000 pods and 260 nodes

### ISSUE THREAD

**Issue by matti** [kontena/lens#5048] opened 2022-03-20 14:35 UTC
similar to https://github.com/lensapp/lens/issues/5041, but with those numbers lens was somewhat usable despite the hangs.

when scaling 15,000 pods (1 cpu req/limit each) and hitting 260+ nodes, the hangs take 10s+ on m1 pro

**Comment by matti** [comment] 2022-03-20 14:37
once the scale up stops, there are less events (or smth) and then it's usable again

**Comment by Nokel81** [comment] 2022-03-21 14:15
Duplicate of https://github.com/lensapp/lens/issues/2243

**Closed as completed by Nokel81** 2022-03-21 14:15 UTC
Labels: bug
