### ISSUE TITLE
Get Prometheus metrics from external prometheus server

### ISSUE THREAD

**Issue by jdalia001** [kontena/lens#7236] opened 2023-02-24 14:04 UTC
Hi,

It could be cool if we can configure an external prometheus server on Lens (When the Prometheus server is not inside the K8S cluster).

**Comment by Nokel81** [comment] 2023-02-27 13:59
Duplicate of https://github.com/lensapp/lens/issues/909

**Closed as not planned by Nokel81** 2023-02-27 13:59 UTC
Labels: enhancement
