### ISSUE TITLE
App crash at `/workloads`

### ISSUE THREAD

**Issue by cedi** [kontena/lens#4418] opened 2021-11-24 23:04 UTC
**Describe the bug**
I just upgraded to Lens 5.2.7-latest.20211110.1 on my Intel MacBook Pro (2019) running macOS BigSur 11.6

**To Reproduce**
1. Go to 'Workloads'
2. Click on 'Overview'
3. See error

**Expected behavior**
See the actual Overview Panel

**Screenshots**
![Screenshot 2021-11-25 at 00 00 07](https://user-images.githubusercontent.com/1952599/143323293-a821b097-0475-4407-9134-35296ede5d0e.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.7-latest.20211110.1
- OS: macOS BigSur 11.6
- Installation method (e.g. snap or AppImage in Linux): dmg

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:

Component stack:
```
    at r (/Users/cedi/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:595820)
    at div
    at div
    at Details
    at div
    at WorkloadsOverview (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:570928:34)
    at Route (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:28658:29)
    at Switch (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:28828:29)
    at ErrorBoundary (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:533193:9)
    at main
    at div
    at http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:521964:16
    at Workloads (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:574202:41)
    at Route (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:28658:29)
    at Switch (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:28828:29)
    at ErrorBoundary (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:533193:9)
    at div
    at div
    at MainLayout (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:533639:9)
    at ErrorBoundary (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:533193:9)
    at Router (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:28321:30)
    at App (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:629958:9)
    at ThemeProvider (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:663422:24)
```

Error stack:
```
TypeError: Cannot read property 'clientWidth' of undefined
    at render (/Users/cedi/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:608021)
    at allowStateChanges (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:1472:12)
    at http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:522408:59
    at trackDerivedFunction (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:2024:18)
    at Reaction.track (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:2552:18)
    at reactiveRender [as render] (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:522406:14)
    at r.makeComponentReactive (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:522421:25)
    at r.target.render (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:522334:34)
    at qi (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:496975:188)
    at pi (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:496974:173)
    at ck (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:497057:427)
    at bk (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:497038:347)
    at ak (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:497038:278)
    at Tj (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:497038:138)
    at Lj (http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:497031:163)
    at http://d07d888cd80523aad831288a18b5bba9.localhost:53550/build/Lens.js:496911:115
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://<REDACTED>:6443
  name: k8s-cedi-dev
contexts:
- context:
    cluster: k8s-cedi-dev
    user: kubernetes-admin
  name: kubernetes-admin@k8s-cedi-dev
current-context: kubernetes-admin@k8s-cedi-dev
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: <REDACTED>
    client-key-data: <REDACTED>


```

**Additional context**
Once the crash happened, it's happening for all the Items below `Workloads`.
However if I click somewhere else (i. E. somewhere below `Configuration` and then to back to `Workloads` without clicking `Overview` (for i. E. `Deployments`) then the Deployment View loads. It only happens when I click `Overview`

**Comment by Nokel81** [comment] 2021-11-25 18:06
Please search previously closed issues as well before opening a new issue. This is a duplicate of #3889 and all other linked duplicates.

The fix is to upgrade your kube-resource-map extension

**Closed as completed by Nokel81** 2021-11-25 18:06 UTC
Labels: bug
