### ISSUE TITLE
5.3.0 ingress bug, cant show details

### ISSUE THREAD

**Issue by minimaco** [kontena/lens#4455] opened 2021-11-30 02:16 UTC
什么鬼，这

![image](https://user-images.githubusercontent.com/20720553/143973928-142527da-ad49-44d7-90f2-a740db259436.png)

**Comment by Nokel81** [comment] 2021-11-30 15:42
Duplicate of https://github.com/lensapp/lens/issues/4443

**Closed as completed by Nokel81** 2021-11-30 15:42 UTC
Labels: bug
