### ISSUE TITLE
Lens 5.4.0 (20220301.1) Multiple Log tabs not working

### ISSUE THREAD

**Issue by mrseanr** [kontena/lens#4978] opened 2022-03-07 19:23 UTC
**Describe the bug**
Opening multiple log tabs to different pods fails to load

**To Reproduce**
1. Go to 'Pods'
2. Click on a pod
3. Click the 'Pod Logs' button
4. A new tab should appear with the pod logs. (working)
5. Now click on a different pod
6. Click the 'Pod Logs' button
7. Another tab should appear with the pod logs. (spinning wheel, no data loads)

**Expected behavior**
All pod logs appear in new tabs and scroll at independent rates (as new log messages appear/independent interval)

**Screenshots**
![Screen Shot 2022-03-07 at 1 19 31 PM](https://user-images.githubusercontent.com/17507370/157103294-8a843e2f-d605-4c51-af79-44d8e03cd3a1.png)
![Screen Shot 2022-03-07 at 1 19 37 PM](https://user-images.githubusercontent.com/17507370/157103302-df398c06-5064-4d15-a0f6-4ca516bc795f.png)

**Environment (please complete the following information):**
- Lens Version: 5.4.0 (20220301.1)
- OS: macOS Monterey
- Installation method (e.g. snap or AppImage in Linux): autoupdate from Lens - Original install from dmg.

**Logs:**
Not running from command line

**Additional context**

**Comment by jim-docker** [comment] 2022-03-07 20:56
Thanks for the report. This is a duplicate of #4958, and has been fixed in 5.4.1

**Closed as completed by jim-docker** 2022-03-07 20:56 UTC
Labels: bug
