### ISSUE TITLE
No cluster metrics on k3s even if I install prometheus-operator

### ISSUE THREAD

**Issue by frederikhors** [kontena/lens#7266] opened 2023-03-03 00:31 UTC
**Describe the bug**
I just installed latest version of Lens on Windows 10.

I just installed a new k3s single node cluster using `curl -sfL https://get.k3s.io | sh -` on Debian 11 (4 core / 16 GB RAM).

I have the message `Metrics are not available due to missing or invalid Prometheus configuration.`.

I tried installing `prometheus-operator` from https://github.com/prometheus-operator/prometheus-operator#quickstart, restarted Lens but still **no cluster metrics**.

Everything else works good.

Why?

**Environment (please complete the following information):**
- Lens Version: 6.4.0
- OS: Win 10

**Comment by Nokel81** [comment] 2023-03-07 14:51
Duplicate of #7264

**Closed as not planned by Nokel81** 2023-03-07 14:51 UTC
Labels: bug

**Comment by frederikhors** [comment] 2023-03-07 17:17
I hope is really a duplicate. But I doubt it.

**Comment by Nokel81** [comment] 2023-03-07 17:23
If you look at the logs do you see anything with `No Prometheus service found`?
