### ISSUE TITLE
Add easy way to update image version in deployment

### ISSUE THREAD

**Issue by kubav182** [kontena/lens#4583] opened 2021-12-16 19:06 UTC
When i want to update image version, I have to open large deployment yaml and search where the version is specified.

Can you add to deployment options button "Update version"? This could open dialog with one field filled with current version and I could update it and save. This functionality is in Kubernetic (similar app to lens).

**Comment by jim-docker** [comment] 2021-12-20 14:00
Duplicate of #4561

**Closed as completed by jim-docker** 2021-12-20 14:00 UTC
Labels: enhancement
