### ISSUE TITLE
Lens does not show anything when connected to Kubernetes cluster

### ISSUE THREAD

**Issue by michaelschem** [kontena/lens#4323] opened 2021-11-11 19:24 UTC
**Describe the bug**
Lens does not show anything in the view when it connects.  It shows the blue light to indicate that it is connected, but the screen is blank.

**To Reproduce**
1. Open Lens
2. Connect to cluster

**Expected behavior**
I expect to be able to see the cluster.

**Screenshots**
![image](https://user-images.githubusercontent.com/2836129/141356318-fa847f6b-fe4e-4921-b0d8-923f41539ceb.png)

**Environment (please complete the following information):**
- Lens Version:
Lens: 5.2.7-latest.20211110.1
Electron: 12.2.2
Chrome: 89.0.4389.128
- OS: 
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
- Installation method: `brew install --cask lens`

**Additional context**
Previously I was having this issue, but when I shared the connection with myself I was able to view it, but not anymore.

**Comment by nfadili** [comment] 2021-11-11 23:32
I am observing similar behavior after upgrading today.

```
Lens: 5.2.7-latest.20211110.1
Electron: 12.2.2
Chrome: 89.0.4389.128
Node: 14.16.0
OS: Big Sur v11.6
```

**Comment by MrDrMcCoy** [comment] 2021-11-12 01:41
This is happening for me as well, but only for one cluster. The cluster that's not working is an AKS cluster in Singapore (I am in Colorado), and the other clusters that work are all in the US (also AKS). Is this a problem with high-latency connections? 

```
Lens: 5.2.7-latest.20211110.1
Electron: 12.2.2
Chrome: 89.0.4389.128
Node: 14.16.0
OS: Arch Linux
```

When launching from the command line, no errors are logged. According to `mtr`, I have a 60% packet loss connecting to this cluster, and an average latency of 450ms. While slow, `k9s` is able to connect to this cluster just fine.

**Comment by michaelschem** [comment] 2021-11-12 01:49
> This is happening for me as well, but only for one cluster. The cluster that's not working is an AKS cluster in Singapore (I am in Colorado), and the other clusters that work are all in the US (also AKS). Is this a problem with high-latency connections?
> 
> ```
> Lens: 5.2.7-latest.20211110.1
> Electron: 12.2.2
> Chrome: 89.0.4389.128
> Node: 14.16.0
> OS: Arch Linux
> ```
> 
> When launching from the command line, no errors are logged. According to `mtr`, I have a 60% packet loss connecting to this cluster, and an average latency of 450ms. While slow, `k9s` is able to connect to this cluster just fine.

I'm trying to connect to a cluster on my LAN with a gig connection, don't think it's that.

**Comment by paulmcarrier** [comment] 2021-11-12 03:00
Was having this issue too. Removing the `~/Library/Application\ Support/Lens` directory restored functionality for me.

**Comment by michaelschem** [comment] 2021-11-12 03:04
@paulmcarrier you are the man! That fixed it for me!

**Comment by gregeedz** [comment] 2021-11-12 23:12
duplicate of #4018

**Closed as completed** 2021-11-15 13:45 UTC
Labels: bug

**Comment by LorenzoLaMura97** [comment] 2023-01-25 09:03
In my case I just pressed command r and it worked.
