### ISSUE TITLE
Helm Release Detail

### ISSUE THREAD

**Issue by bhdryrdm** [kontena/lens#7128] opened 2023-02-09 07:26 UTC
**Describe the bug**
Hi,

When I want to view the details of any of the Helm releases, the details of the first opened release after the application starts are always displayed.

**To Reproduce**
1. Go to 'Helm > Releases'
2. Click on 'Any Release on the List'
3. Click on 'Any Other Release on the List'
4. You will see the release detail, which you click on the first detail.

**Expected behavior**
I'm waiting to view the release detail I clicked on, but I suspect there is a cache here.

**Screenshots**
Not available. 

**Environment (please complete the following information):**
- Lens Version: 2023.1.110749-latest
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Downloading Lens Desktop File

**Comment by Nokel81** [comment] 2023-02-13 13:55
Duplicate of https://github.com/lensapp/lens/issues/6721

**Closed as completed by Nokel81** 2023-02-13 13:55 UTC
Labels: bug
