### ISSUE TITLE
Preserved text in search field

### ISSUE THREAD

**Issue by riwarek** [kontena/lens#5625] opened 2022-06-14 13:45 UTC
**What would you like to be added**:
Search text should be preserved after tab has been switched (eg. from pods to deployments).

**Why is this needed**:
Because when I switch the tabs I have to type filtered text over and over again.

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] have no idea
- Desktop OS: Ubuntu

**Comment by Nokel81** [comment] 2022-06-14 14:36
Duplicate of #3510

**Closed as not planned by Nokel81** 2022-06-14 14:36 UTC
Labels: enhancement
