### ISSUE TITLE
After upgrading to 5.3.0-latest.20211125.2, node CPU and disk monitoring are not displayed

### ISSUE THREAD

**Issue by zhangmengid** [kontena/lens#4456] opened 2021-11-30 03:01 UTC
升级到5.3.0后node节点cpu和disk监控不显示

**Comment by zhangmengid** [comment] 2021-11-30 05:34
![image](https://user-images.githubusercontent.com/83331571/143991241-efbcc4a7-facd-4687-9935-eab531b974b7.png)

**Comment by Nokel81** [comment] 2021-11-30 15:42
Are you able to translate your issue into English? What metrics operator setting is set?

**Comment by zhangmengid** [comment] 2021-12-01 00:45
After upgrading to 5.3.0, node  CPU and disk monitoring are not displayed

**Comment by renaudhager** [comment] 2021-12-01 10:58
I have the same issue. 
To more details, when we go on a specific node we are able to get all the metrics:
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/12563305/144222203-6a0df3ab-dc43-4cc5-96d8-5431155a0762.png">
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/12563305/144222231-9423d980-cda3-4324-8d80-25b4d2547e76.png">
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/12563305/144222255-6973a9f7-9ed5-4114-b020-84f246d7ebee.png">

The cluster overview is also broken: 
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/12563305/144222305-30f13acc-f6c9-4cb9-976e-28577d89fd28.png">

Lens version:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/12563305/144222436-edb775d2-3782-40ad-a5f1-58360176378c.png">

**Comment by vitaliyf** [comment] 2021-12-01 16:02
Is this possibly related to label changes such as https://github.com/prometheus-community/helm-charts/pull/1520 ?

**Comment by Nokel81** [comment] 2021-12-01 16:04
Yes it could be...

**Comment by agentq15** [comment] 2021-12-02 14:02
We have the same issue

**Comment by bravecobra** [comment] 2021-12-02 17:04
Seems to be a duplicate of #4435

**Comment by Nokel81** [comment] 2021-12-02 17:05
Yes @bravecobra, good catch. Will close this in favour of that.

**Closed as completed by Nokel81** 2021-12-02 17:05 UTC
Labels: bug, area/metrics
