### ISSUE TITLE
[Fedora 34] - Installation conflicts with Draw.io

### ISSUE THREAD

**Issue by weyderfs** [kontena/lens#4525] opened 2021-12-07 12:34 UTC
**Describe the bug**
I'm trying installs using the `$ sudo dnf install Lens-5.3.2-latest.20211201.1.x86_64.rpm`.

**To Reproduce**
Just try install.

```
sudo dnf install ~/Downloads/Lens-5.3.2-latest.20211201.1.x86_64.rpm 
[sudo] password for darth: 
Last metadata expiration check: 0:21:46 ago on ter 07 dez 2021 09:04:25.
Dependencies resolved.
==============================================================================================================================================================================================
 Package                            Architecture                         Version                                                             Repository                                  Size
==============================================================================================================================================================================================
Upgrading:
 lens                               x86_64                               5.3.2_latest.20211201.1-20211201.1                                  @commandline                               106 M

Transaction Summary
==============================================================================================================================================================================================
Upgrade  1 Package

Total size: 106 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/lib/.build-id/3c/f3dce1c9e94bdf4e5ae52a57a14e8b02f3e2cf from install of lens-5.3.2_latest.20211201.1-20211201.1.x86_64 conflicts with file from package draw.io-15.8.7-1.x86_64
  file /usr/lib/.build-id/4b/d1434c7f9139c9e65deb95dad4693bf522e713 from install of lens-5.3.2_latest.20211201.1-20211201.1.x86_64 conflicts with file from package draw.io-15.8.7-1.x86_64
  file /usr/lib/.build-id/63/a48eae3f41e679c8ca2735c8250de0c7d9f587 from install of lens-5.3.2_latest.20211201.1-20211201.1.x86_64 conflicts with file from package draw.io-15.8.7-1.x86_64
  file /usr/lib/.build-id/ba/ced248fd6f456e45c904f72299073c22f5b064 from install of lens-5.3.2_latest.20211201.1-20211201.1.x86_64 conflicts with file from package draw.io-15.8.7-1.x86_64
  file /usr/lib/.build-id/e8/75bf159c6409cfeb2471b9e8f4bb917b67a4e0 from install of lens-5.3.2_latest.20211201.1-20211201.1.x86_64 conflicts with file from package draw.io-15.8.7-1.x86_64
  file /usr/lib/.build-id/f9/5ad887e13e9f4ceb539f8b9375c198875cf2e0 from install of lens-5.3.2_latest.20211201.1-20211201.1.x86_64 conflicts with file from package draw.io-15.8.7-1.x86_64
  file /usr/lib/.build-id/fc/45cc0e8eeb65dbed3d516283e3b7903f59fc1f from install of lens-5.3.2_latest.20211201.1-20211201.1.x86_64 conflicts with file from package draw.io-15.8.7-1.x86_64
```
**Environment (please complete the following information):**
- Lens Version: `5.3.2_latest.20211201.1-20211201.1`
- OS:
```
cat /etc/[A-Za-z]*[_-][rv]e[lr]*
Fedora release 34 (Thirty Four)
NAME=Fedora
VERSION="34 (Workstation Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 34 (Thirty Four)
Fedora release 34 (Thirty Four)
cpe:/o:fedoraproject:fedora:34
```
- Installation method: `dnf, rpm`

**Comment by Nokel81** [comment] 2021-12-07 15:17
Duplicate of  #4449

**Closed as completed by Nokel81** 2021-12-07 15:17 UTC
Labels: bug
