### ISSUE TITLE
White Square on main window

### ISSUE THREAD

**Issue by DarkNightHome** [kontena/lens#6171] opened 2022-09-04 17:00 UTC
**Describe the bug**
When open app show on bottom right white square

**To Reproduce**
Install and run

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: Windows 11
- Installation method installer

![image](https://user-images.githubusercontent.com/6933642/188324890-9f62ad92-06d4-4e95-b1e5-9e7b952e0133.png)

**Comment by wilsoncg** [comment] 2022-09-04 17:23
I'm also seeing this too.
What is it that has failed to render?

Win 10
Lens 6.0.1-latest

![image](https://user-images.githubusercontent.com/1066103/188325701-0f28f35d-c2af-4a72-aa6b-93620713561f.png)

**Comment by Nokel81** [comment] 2022-09-06 14:53
This will be fixed in the next patch release. 

Duplicate of #6169

**Closed as not planned by Nokel81** 2022-09-06 14:53 UTC
Labels: bug
