### ISSUE TITLE
lens ui / terminal hangs with 10,000 pods and 163 nodes

### ISSUE THREAD

**Issue by matti** [kontena/lens#5041] opened 2022-03-18 12:52 UTC
please see the video [SOUND ON]

https://user-images.githubusercontent.com/3893/159006145-cc65d0e8-2033-4685-b014-1b94858770a8.mov

**Comment by matti** [comment] 2022-03-19 08:29
and runs on macos mbp16 m1 pro

**Comment by Nokel81** [comment] 2022-03-21 14:15
Duplicate of https://github.com/lensapp/lens/issues/2243

**Closed as completed by Nokel81** 2022-03-21 14:15 UTC
Labels: bug

**Comment by aleksfront** [comment] 2022-03-28 11:21
@matti Can I ask you testing this one with your cluster? https://github.com/lensapp/lens/pull/5114

You can checkout into the `fix-big-cluster-table-freeze` branch, download the contents and make 
```
yarn && yarn build:mac
```
and start `OpenLens` from `/dist` folder.

**Comment by matti** [comment] 2022-03-28 13:54
@aleksfront since that is merged, when is it going to get released? not sure if I have time before the release
