### ISSUE TITLE
Issues with RBAC and k8slens

### ISSUE THREAD

**Issue by pjaak** [kontena/lens#3923] opened 2021-10-01 05:45 UTC
**Describe the bug**
We have many teams in our organization so we use namespace RBAC. We also have lots of namespaces, maybe 50 plus. When we set rbac rules for some namespaces we get nothing on the lens dashboard.

**Environment (please complete the following information):**
- Lens Version: 5.2.2
- OS: MacOS Catalina
- Installation method (e.g. snap or AppImage in Linux): Download from website

**Additional context**
I believe something was mentioned here about the permissions are only taken from the top then namespaces:
https://github.com/lensapp/lens/issues/2609
I did do some testing and found that when the RBAC was set on a top ten namespace it worked but not when it was below the top 10. I can see there was a PR targeted for v5 but it seems to have been closed?

**Comment by Nokel81** [comment] 2021-10-01 15:38
Yes, sorry that you have run into that bug. Yes that PR was closed because it introduced a massive performance hit when a cluster had a lot of namespaces. We know about this issue but won't be able to focus our efforts on it for a little bit.

I am going to close this as a duplicate of #2609

**Closed as completed by Nokel81** 2021-10-01 15:38 UTC
Labels: bug
