### ISSUE TITLE
executable kubelogin not found after upgrading to v6.0.2

### ISSUE THREAD

**Issue by davyrod** [kontena/lens#6257] opened 2022-09-15 15:55 UTC
**Describe the bug**
I have been using Lens IDE for some time with no issues.  After a recent upgrade to the latest version, v6.0.2, I am now unable to connect to my AKS clusters and receive the following error:

```
'E0915 10:52:48.440909 21640 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable kubelogin not found
```

getting credentials: exec: executable kubelogin not found'

**To Reproduce**
1. Open Lens IDE
2. Attempt to Connect to any AKS cluster

**Expected behavior**
Login to AKS cluster should succeed. 

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: v6.0.2-latest
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Windows .exe download
- Running kubectl and kubelogin within WSL2

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
E0915 10:52:48.440909 21640 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable kubelogin not found

getting credentials: exec: executable kubelogin not found
```

**Comment by Nokel81** [comment] 2022-10-03 13:11
Duplicate of https://github.com/lensapp/lens/issues/6238. For some reason shell sync sometimes doesn't work. Does running Lens from the terminal fix this issue?

**Closed as not planned by Nokel81** 2022-10-03 13:11 UTC
Labels: bug
