### ISSUE TITLE
App crash at /cluster

### ISSUE THREAD

**Issue by djnew** [kontena/lens#3942] opened 2021-10-02 21:53 UTC
Component stack:
    at http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:9707:16
    at div
    at div
    at div
    at InfoPanel (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:662730:9)
    at div
    at Logs (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:664755:9)
    at div
    at div
    at Dock (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:665167:9)
    at div
    at div
    at MainLayout (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:572652:9)
    at ErrorBoundary (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:572113:47)
    at ErrorBoundary (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:572222:36)
    at Router (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:32134:30)
    at App (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:666393:9)
    at ThemeProvider (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:700069:24)

TypeError: Cannot read property 'namespace' of undefined
    at pods_api_Pod.getNs (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:588819:30)
    at pods_api_Pod.getOwnerRefs (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:588850:32)
    at http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:663994:30
    at http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:9707:49
    at http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:9671:25
    at trackDerivedFunction (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:2024:18)
    at Reaction.track (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:2552:18)
    at useObserver (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:9669:14)
    at http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:9707:16
    at Ch (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535650:137)
    at li (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535673:154)
    at ki (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535671:169)
    at ii (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535670:178)
    at ck (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535767:126)
    at bk (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535743:347)
    at ak (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535743:278)
    at Tj (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535743:138)
    at Lj (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535736:163)
    at http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535616:115
    at exports.unstable_runWithPriority (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535827:343)
    at gg (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535615:325)
    at jg (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535616:61)
    at ig (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535615:428)
    at Wj (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:535737:190)
    at reactionScheduler (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:2679:12)
    at http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:2680:14
    at Gh (C:\Users\djnew\AppData\Local\Programs\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:347:141185)
    at reactionScheduler (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:2679:12)
    at runReactions (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:2648:3)
    at endBatch (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:2315:5)
    at transaction (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:3471:5)
    at ObservableMap.replace (http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:4484:5)
    at http://239fff2b08791ad5cc91209900b2ab44.localhost:49559/build/Lens.js:596921:27

**Comment by Nokel81** [comment] 2021-10-04 13:21
Duplicate of https://github.com/lensapp/lens/issues/3543

**Closed as completed by Nokel81** 2021-10-04 13:21 UTC
Labels: bug
