### ISSUE TITLE
Don't apply namespace filter to node's Pods

### ISSUE THREAD

**Issue by pnorth1** [kontena/lens#5243] opened 2022-04-14 23:36 UTC
If you have a namespace filter applied when viewing Pods, and select the Pod's node, the node view will only show Pod's in that namespace. I think it would be more appropriate to show all pods on the Node in this case.

**Comment by Nokel81** [comment] 2022-04-19 13:00
Duplicate of https://github.com/lensapp/lens/issues/4811

**Closed as completed by Nokel81** 2022-04-19 13:00 UTC
Labels: enhancement
