### ISSUE TITLE
Control-S or Command-S (mac) should save the contents of the open panel, if applicable

### ISSUE THREAD

**Issue by richard-fairthorne** [kontena/lens#6814] opened 2022-12-22 02:58 UTC
**What would you like to be added**:
When editing a resource, CTRL-S or CMD-S on mac should behave the same as pressing the "save" button.

**Why is this needed**:
These are universal idioms that help programmers and operators work more quickly. If you are iterating on improvements to a chart or config map, this shortcut saves time. Keyboard shortcuts are big time savers.

**Environment you are Lens application on:**

- Kubernetes distribution: multiple distributions
- Desktop OS: osx Ventura

**Comment by Nokel81** [comment] 2023-01-03 14:03
Duplicate of https://github.com/lensapp/lens/issues/177 and others. This is indeed a very good idea. Will work on getting this a prioritisation.

**Closed as not planned by Nokel81** 2023-01-03 14:03 UTC
Labels: enhancement
