### ISSUE TITLE
Lens update to 5.2.0-latest.20210908.1 - clusters accessible namespaces are reset every time the application is closed

### ISSUE THREAD

**Issue by rajeshkarupakala5** [kontena/lens#3816] opened 2021-09-15 15:30 UTC
I recently updated Lens to 5.2.0-latest.20210908.1
After the update, clusters accessible namespaces gets reset every time I close the app. I have to add them back every time.

If you right click on one of the K8s clusters, and go to settings, we have a option to add accessible namespaces. 
After the update, the namespaces I added gets removed when I close the application. I have to add them every single time.

![image](https://user-images.githubusercontent.com/26311213/133463324-b7465d7a-10f0-4d64-a61d-956dbdc4a92f.png)

**Comment by nevalla** [comment] 2021-09-15 15:56
Duplicate of #3815.

**Closed as completed by nevalla** 2021-09-15 15:56 UTC
Labels: duplicate
