### ISSUE TITLE
Left and Right pane disappears

### ISSUE THREAD

**Issue by tahirali-endurance** [kontena/lens#3893] opened 2021-09-24 14:44 UTC
**Describe the bug**
We connect to cluster and when Lens is about show the cluster object., the left and right appears completely blank and not showing anything

**To Reproduce**
1. Connect to Cluster
2. The left and right disappears completely.

**Expected behavior**
The cluster information should appear

**Screenshots**
<img width="1731" alt="Screen Shot 2021-09-24 at 9 34 05 AM" src="https://user-images.githubusercontent.com/61319327/134692601-1bb514d3-fd50-475e-bd08-67ef5dd214c3.png">

**Environment (please complete the following information):**
- Lens Version: Lens: 5.2.4-latest.20210923.1
- OS: MacOS
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1417

- Installation method (e.g. snap or AppImage in Linux):
Apple dmg file

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register succeeded ✅ +3ms
info:    ▪ 🚀 Starting Lens from "/Applications/Lens.app/Contents/MacOS/Lens" +103ms
info:    ▪ 🐚 Syncing shell environment +1ms
info:    ▪ 💾 Loading stores +2s
info:    ▪ [BS]: LOADED from /Users/miali/Library/Application Support/Lens/lens-user-store.json +39ms
info:    ▪ [DA]: LOADED from /Users/miali/Library/Application Support/Lens/lens-cluster-store.json +44ms
info:    ▪ [NU]: LOADED from /Users/miali/Library/Application Support/Lens/lens-hotbar-store.json +4ms
info:    ▪ [MT]: LOADED from /Users/miali/Library/Application Support/Lens/lens-extensions.json +2ms
info:    ▪ [C]: LOADED from /Users/miali/Library/Application Support/Lens/lens-filesystem-provisioner-store.json +2ms
info:    ▪ [KA]: LOADED from /Users/miali/Library/Application Support/Lens/lens-weblink-store.json +3ms
info:    ▪ 🔌 Starting LensProxy +10ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:59354 +4ms
info:    ▪ 🔎 Testing LensProxy connection ... +1ms
info:    ▪ ⚡ LensProxy connection OK +117ms
info:    ▪ 🖥️  Starting WindowManager +4ms
info:    ▪ 🧩 Initializing extensions +59ms
info:    ▪ [EXTENSION-DISCOVERY] loading extensions from /Users/miali/Library/Application Support/Lens +0ms
info:    ▪ [EXTENSION-INSTALLER] installing dependencies at /Users/miali/Library/Application Support/Lens +57ms
info:    ▪ [WINDOW-MANAGER]: Loading Main window from url: http://localhost:59354 ... +181ms
info:    ▪ [EXTENSION-INSTALLER] dependencies installed at /Users/miali/Library/Application Support/Lens +820ms
info:    ▪ [EXTENSION-DISCOVERY] watching extension add/remove in /Users/miali/.k8slens/extensions +6ms
Native extraction module not loaded, msgpackr will still run, but with decreased performance. Cannot find module 'msgpackr-extract'
Lens Cloud Extension activated
info:    ▪ [C]: LOADED from /Users/miali/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/auth-token-store.json +68ms
info:    ▪ [C]: LOADED from /Users/miali/Library/Application Support/Lens/extension-store/lens-survey/preferences-store.json +4ms
telemetry main extension activated
info:    ▪ [N]: LOADED from /Users/miali/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json +48ms
[@mirantis/lens-extension-cc/ExtensionMain.onActivate()] extension activated
info:    ▪ [PREFERENCE-STORE]: LOADED from /Users/miali/Library/Application Support/Lens/extension-store/@mirantis/lens-extension-cc/preference-store.json +40ms
info:    ▪ [CLUSTER-STORE]: LOADED from /Users/miali/Library/Application Support/Lens/extension-store/@mirantis/lens-extension-cc/cluster-store.json +2ms
[@mirantis/lens-extension-cc/IpcMain.restoreClusters()] Restored 0 clusters from clusterStore into catalog, clusters=[]
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┗ [1] { channel: 'addClusters', extension: { name: '@mirantis/lens-extension-cc', version: '3.0.3' } }
info:    ┏ [IPC-RENDERER]: adding extension handler +2ms
info:    ┗ [1] { channel: 'removeCluster', extension: { name: '@mirantis/lens-extension-cc', version: '3.0.3' } }
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┗ [1] { channel: 'deleteCluster', extension: { name: '@mirantis/lens-extension-cc', version: '3.0.3' } }
info:    ▪ [STORE]: SAVING /Users/miali/Library/Application Support/Lens/lens-extensions.json +6ms
info:    ┏ [IPC-RENDERER]: adding extension listener +109ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'deleteOneCluster',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.4-latest.20210923.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'loadRemoteSpacesClusters',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.4-latest.20210923.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'createOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.4-latest.20210923.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'leaveOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.4-latest.20210923.1' }
info:    ┗ [4] }
info:    ▪ [EXTENSION]: enabled lens-license@5.2.4-latest.20210923.1 +69ms
info:    ▪ [EXTENSION]: enabled @mirantis/lens-extension-cc@3.0.3 +4ms
info:    ▪ [EXTENSION]: enabled lens-survey@5.2.4-latest.20210923.1 +0ms
info:    ▪ [EXTENSION]: enabled lens-telemetry@5.2.4-latest.20210923.1 +1ms
[CLUSTER-CONNECT] cluster proxy started on port 59369
[CLUSTER-CONNECT] cluster proxy is using aes-256-gcm for end-to-end encryption
info:    ▪ [EXTENSION]: enabled lenscloud-lens-extension@5.2.4-latest.20210923.1 +64ms
info:    ▪ [WINDOW-MANAGER]: Main window loaded +846ms
info:    ▪ [KUBECONFIG-SYNC]: starting requested syncs +500ms
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +0ms
info:    ┗ [1] { filePath: '/Users/miali/Library/Application Support/Lens/kubeconfigs' }
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +1ms
info:    ┗ [1] { filePath: '/Users/miali/.kube' }
info:    ▪ 📡 Checking for app updates +1ms
info:    ▪ Checking for update +0ms
info:    ▪ [KUBECONFIG-SYNC]: ignoring '/Users/miali/.kube/config.eksctl.lock' due to ignore glob: *.lock +8ms
info:    ▪ [WINDOW-MANAGER]: Main window has reported that it has loaded +41ms
info:    ▪ [WINDOW-MANAGER]: Attaching webview +554ms
info:    ▪ Update for version 5.2.4-latest.20210923.1 is not available (latest version: 5.2.4-latest.20210923.1, downgrade is disallowed). +155ms
info:    ┏ [CLUSTER]: activate +4s
info:    ┃ [1] {
info:    ┃ [2]   id: '1a21faf5e741741bc09102d60a087562',
info:    ┃ [3]   name: '1632433791183977000@capi.us-east-1.eksctl.io',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: bind events +1ms
info:    ┃ [1] {
info:    ┃ [2]   id: '1a21faf5e741741bc09102d60a087562',
info:    ┃ [3]   name: '1632433791183977000@capi.us-east-1.eksctl.io',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: reconnect +0ms
info:    ┃ [1] {
info:    ┃ [2]   id: '1a21faf5e741741bc09102d60a087562',
info:    ┃ [3]   name: '1632433791183977000@capi.us-east-1.eksctl.io',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [KUBE-AUTH]: out-channel "kube-auth:1a21faf5e741741bc09102d60a087562" +843ms
info:    ┃ [ 1] {
info:    ┃ [ 2]   data: 'Authentication proxy started\n',
info:    ┃ [ 3]   meta: {
info:    ┃ [ 4]     id: '1a21faf5e741741bc09102d60a087562',
info:    ┃ [ 5]     name: '1632433791183977000@capi.us-east-1.eksctl.io',
info:    ┃ [ 6]     ready: false,
info:    ┃ [ 7]     online: false,
info:    ┃ [ 8]     accessible: false,
info:    ┃ [ 9]     disconnected: true
info:    ┃ [10]   }
info:    ┗ [11] }
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <<Secret Data>>
    server: <<URL>>
contexts:
- context:
    cluster: capi.us-east-1.eksctl.io
    user: <<USER>>
  name: 1632433791183977000@capi.us-east-1.eksctl.io
current-context: 1632433791183977000@capi.us-east-1.eksctl.io
kind: Config
preferences: {}
users:
- name: 1632433791183977000@capi.us-east-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - capi
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: us-east-1
```

**Comment by robertd** [comment] 2021-09-24 19:30
Same here... running latest version on Big Sur.
![image](https://user-images.githubusercontent.com/31543/134729992-e982e85a-2ef6-4c9b-a84a-43b46bbf5c27.png)

**Comment by Nokel81** [comment] 2021-09-27 13:12
If you disconnect and reconnect, or go back to the catalog and then back to the cluster does the issue persist?

@tahirali-endurance Is there ever any more logs after the `[KUBE-AUTH]: out-channel "kube-auth:1a21faf5e741741bc09102d60a087562" +843ms` line?

**Comment by tahirali-endurance** [comment] 2021-09-27 14:17
Well, neither disconnect, reconnect or going back and forth resolved the issue. That's what I see:
```
info:    ┏ [KUBE-AUTH]: out-channel "kube-auth:1a21faf5e741741bc09102d60a087562" +2s
info:    ┃ [ 1] {
info:    ┃ [ 2]   data: 'Authentication proxy started\n',
info:    ┃ [ 3]   meta: {
info:    ┃ [ 4]     id: '1a21faf5e741741bc09102d60a087562',
info:    ┃ [ 5]     name: '1632433791183977000@capi.us-east-1.eksctl.io',
info:    ┃ [ 6]     ready: false,
info:    ┃ [ 7]     online: false,
info:    ┃ [ 8]     accessible: false,
info:    ┃ [ 9]     disconnected: true
info:    ┃ [10]   }
info:    ┗ [11] }
info:    ┏ [CLUSTER]: refresh +28s
info:    ┃ [1] {
info:    ┃ [2]   id: '1a21faf5e741741bc09102d60a087562',
info:    ┃ [3]   name: '1632433791183977000@capi.us-east-1.eksctl.io',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +30s
info:    ┃ [1] {
info:    ┃ [2]   id: '1a21faf5e741741bc09102d60a087562',
info:    ┃ [3]   name: '1632433791183977000@capi.us-east-1.eksctl.io',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +30s
info:    ┃ [1] {
info:    ┃ [2]   id: '1a21faf5e741741bc09102d60a087562',
info:    ┃ [3]   name: '1632433791183977000@capi.us-east-1.eksctl.io',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +30s
info:    ┃ [1] {
info:    ┃ [2]   id: '1a21faf5e741741bc09102d60a087562',
info:    ┃ [3]   name: '1632433791183977000@capi.us-east-1.eksctl.io',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }

```

**Comment by krisztian-sala** [comment] 2021-09-30 05:25
I have the same issue. Deleting the cluster from kubeconfig and readding solved it for a few hours, but now it is the same and can't do anything to fix it. I have 3 clusters and the problem persists with only 1 of them

**Comment by Nokel81** [comment] 2021-09-30 13:39
I need to renderer logs, if you open up devtools would you be able to paste the logs from its console?

**Comment by Nokel81** [comment] 2021-09-30 15:10
I think this is a duplicate of https://github.com/lensapp/lens/issues/3829 so I am going to close this, please add some logs to that issue.

**Closed as completed by Nokel81** 2021-09-30 15:10 UTC
Labels: bug

**Comment by tahirali-endurance** [comment] 2021-09-30 15:17
This above issues relates to Windows and I am still facing the issue. These are the logs
```
[USER-STORE-USER-STORE]: LOADED from /Users/miali/Library/Application Support/Lens/lens-user-store.json
instrument.js:109 [CLUSTER-STORE-CLUSTER-STORE]: LOADED from /Users/miali/Library/Application Support/Lens/lens-cluster-store.json
instrument.js:109 [CLUSTER-STORE] requesting initial state sync
instrument.js:109 [HOTBAR-STORE-HOTBAR-STORE]: LOADED from /Users/miali/Library/Application Support/Lens/lens-hotbar-store.json
instrument.js:109 [EXTENSIONS-STORE-EXTENSIONS-STORE]: LOADED from /Users/miali/Library/Application Support/Lens/lens-extensions.json
instrument.js:109 [EXTENSION-FILESYSTEM-FILESYSTEM-PROVISIONER-STORE]: LOADED from /Users/miali/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
instrument.js:109 [WEBLINK-STORE-WEBLINK-STORE]: LOADED from /Users/miali/Library/Application Support/Lens/lens-weblink-store.json
instrument.js:109 [CLUSTER-STORE] start to listen (1)
instrument.js:109 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
instrument.js:109 Lens Cloud Extension activated
instrument.js:109 [L]: LOADED from /Users/miali/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/auth-token-store.json
instrument.js:109 [D]: LOADED from /Users/miali/Library/Application Support/Lens/extension-store/lens-survey/preferences-store.json
instrument.js:109 telemetry extension activated
instrument.js:109 [N]: LOADED from /Users/miali/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json
instrument.js:109 [@mirantis/lens-extension-cc/ExtensionRenderer.onActivate()] extension activated
instrument.js:109 [PREFERENCE-STORE]: LOADED from /Users/miali/Library/Application Support/Lens/extension-store/@mirantis/lens-extension-cc/preference-store.json
instrument.js:109 [CLUSTER-STORE]: LOADED from /Users/miali/Library/Application Support/Lens/extension-store/@mirantis/lens-extension-cc/cluster-store.json
instrument.js:109 [IPC-RENDERER]: adding extension listener Object
instrument.js:109 [PROTOCOL ROUTER]: internal registering /preferences
instrument.js:109 [PROTOCOL ROUTER]: internal registering /
instrument.js:109 [PROTOCOL ROUTER]: internal registering /landing
instrument.js:109 [PROTOCOL ROUTER]: internal registering /landing/view/:group/:kind
instrument.js:109 [PROTOCOL ROUTER]: internal registering /cluster
instrument.js:109 [PROTOCOL ROUTER]: internal registering /entity/:entityId/settings
instrument.js:109 [PROTOCOL ROUTER]: internal registering /cluster/:clusterId
instrument.js:109 [PROTOCOL ROUTER]: internal registering /cluster/:clusterId/settings
instrument.js:109 [PROTOCOL ROUTER]: internal registering /extensions
instrument.js:109 [PROTOCOL ROUTER]: internal registering /extensions/install/:LENS_INTERNAL_EXTENSION_PUBLISHER_MATCH(@[A-Za-z0-9_]+)?/:LENS_INTERNAL_EXTENSION_NAME_MATCH
instrument.js:109 [EXTENSION]: enabled kube-object-event-status@5.2.4-latest.20210923.1
instrument.js:109 [EXTENSION]: enabled lens-metrics-cluster-feature@5.2.4-latest.20210923.1
instrument.js:109 [EXTENSION]: enabled lens-node-menu@5.2.4-latest.20210923.1
instrument.js:109 [EXTENSION]: enabled lens-pod-menu@5.2.4-latest.20210923.1
instrument.js:109 [EXTENSION]: enabled @mirantis/lens-extension-cc@3.0.3
instrument.js:109 [EXTENSION]: enabled lens-survey@5.2.4-latest.20210923.1
instrument.js:109 [EXTENSION]: enabled lens-telemetry@5.2.4-latest.20210923.1
instrument.js:109 [@mirantis/lens-extension-cc/IpcMain.restoreClusters()] Restored 0 clusters from clusterStore into catalog, clusters=[]
instrument.js:109 Running Auth Callback Server on http://localhost:58961
instrument.js:109 [StorageHelper]: loading finished for /Users/miali/Library/Application Support/Lens/lens-local-storage/app.json
instrument.js:109 Running CORS Anywhere Proxy on http://localhost:58962/
instrument.js:109 Can't access https://k8slens.dev/welcome_banners/welcome_banner_02.html
(anonymous) @ instrument.js:109
instrument.js:109 Can't access https://k8slens.dev/welcome_banners/welcome_banner_01.html
(anonymous) @ instrument.js:109
instrument.js:109 Can't access https://k8slens.dev/welcome_banners/welcome_banner_03.html
(anonymous) @ instrument.js:109
instrument.js:109 Can't access https://k8slens.dev/welcome_banners/welcome_banner_04.html
(anonymous) @ instrument.js:109
instrument.js:109 Can't access https://k8slens.dev/welcome_banners/welcome_banner_05.html
(anonymous) @ instrument.js:109
instrument.js:109 [EXTENSION]: enabled lenscloud-lens-extension@5.2.4-latest.20210923.1
instrument.js:109 [StorageHelper]: saving /Users/miali/Library/Application Support/Lens/lens-local-storage/app.json
instrument.js:109 [LENS-VIEW]: refreshing iframe views, visible cluster id=1a21faf5e741741bc09102d60a087562
instrument.js:109 [LENS-VIEW]: init dashboard, clusterId=1a21faf5e741741bc09102d60a087562
instrument.js:109 [LENS-VIEW]: waiting cluster to be ready, clusterId=1a21faf5e741741bc09102d60a087562
instrument.js:109 [LENS-VIEW]: cluster is ready, clusterId=1a21faf5e741741bc09102d60a087562
instrument.js:109 [LENS-VIEW]: loaded from http://1a21faf5e741741bc09102d60a087562.localhost:58930/
```

**Comment by Nokel81** [comment] 2021-09-30 15:22
@tahirali-endurance do you mean the linked issue? If so then no, it is not just a windows issue. Initial report was from a linux user and macOS users have also commented. The symptoms are basically the same which is why I think it is a duplicate.

**Comment by tahirali-endurance** [comment] 2021-09-30 15:26
I still see the same issue and I think I have updated to latest version. 
```
Lens: 5.2.4-latest.20210923.1
Electron: 12.0.17
Chrome: 89.0.4389.128
Node: 14.16.0
© 2021 Mirantis, Inc.
```

**Comment by robertd** [comment] 2021-10-05 02:56
I've updated Lens to the latest version and right pane seems to be working now... 
![image](https://user-images.githubusercontent.com/31543/135952981-ac816027-a59d-4b25-a64a-c70ce128b25c.png)
