### ISSUE TITLE
i can't configure lens on mac

### ISSUE THREAD

**Issue by samuelbartels20** [kontena/lens#4409] opened 2021-11-24 09:50 UTC
Hello Team,
I am trying to setup up lens to connect to my cluster on Mac but each time i get the below error
Any tip from the team will be highly appreciative

<img width="1089" alt="Screenshot 2021-11-24 at 09 35 13" src="https://user-images.githubusercontent.com/40799981/143215249-6d951edd-0ad1-4c67-9870-7d216bc4e43d.png">
.

**Comment by Nokel81** [comment] 2021-11-24 14:14
Duplicate of https://github.com/lensapp/lens/issues/4410

**Closed as completed by Nokel81** 2021-11-24 14:14 UTC
