### ISSUE TITLE
Add folders or workspaces to cluster catalog

### ISSUE THREAD

**Issue by Scarjit** [kontena/lens#5422] opened 2022-05-19 09:33 UTC
**What would you like to be added**:
I would like to have folders or workspaces to sort the clusters i have to manage.

**Why is this needed**:
At the moment i have per customer ~10 different kubernetes clusters, which are all listed, without sorting.

Having the option to add folders or select different *local* workspaces would be great.

I can't sort them by using Team Spaces, due to company policies, regarding the upload of private keys.

**Environment you are Lens application on:**

- Kubernetes distribution: Not relevant, but k3os/rancher
- Desktop OS: Windows 11

**Comment by Nokel81** [comment] 2022-05-20 12:31
Thanks for the request, but I am going to mark this as a duplicate of https://github.com/lensapp/lens/issues/2602

**Closed as not planned by Nokel81** 2022-05-20 12:31 UTC
Labels: enhancement
