### ISSUE TITLE
Can't change the width of the columns

### ISSUE THREAD

**Issue by emoxam** [kontena/lens#6980] opened 2023-01-19 09:18 UTC
Can't change the width of the columns

**To Reproduce**
1. Go to 'Workloads'
2. Click on 'Overview'
3. Try to 'change any columt
4. See the cursor not changing to needed

**Expected behavior**
Cursor must changes to needed view

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 2023.1.110749-latest
- OS: Windows 11 22h2

**Comment by Nokel81** [comment] 2023-01-23 13:50
Duplicate of #601

**Closed as not planned by Nokel81** 2023-01-23 13:50 UTC
Labels: bug
