### ISSUE TITLE
App crash at /helm/releases/

### ISSUE THREAD

**Issue by sj-porter-knime** [kontena/lens#6030] opened 2022-08-12 18:15 UTC
**Describe the bug**
The Lens app crashes when attempting to view a selected Helm release in the sidebar. This issue is occurring for me across multiple clusters and Helm releases.

**To Reproduce**
1. Download Lens .dmg on MacOS Monterey.
2. Create a cluster and connect.
3. Install one or more helm releases.
4. Navigate to `Helm` --> `Releases` in the navigation pane.
5. Click on a Helm release to attempt to view it.
6. The error below will display within a few seconds.

**Expected behavior**
The typical Helm release view/edit pane (right sidebar) should display with information and statuses visible.

**Screenshots**

A few seconds after selecting a helm release to be monitored in the sidebar, the following appears:

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/86624823/184418556-a3ddbfb4-8ec1-4caf-9589-ab077c979e8a.png">

**Environment (please complete the following information):**
- Lens Version: 
  - Lens: 6.0.0-latest.20220728.2
  - Electron: 15.5.7
  - Chrome: 94.0.4606.81
  - Node: 16.5.0
- OS: MacOS Monterey version 12.5 (21G72)
- Installation method (e.g. snap or AppImage in Linux): MacOS .dmg download

**Logs:**

```
Component stack:


    at NonInjectedMonacoEditor (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:609353:9)
    at div
    at div
    at observerComponent (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:240471:16)
    at div
    at div
    at div
    at div
    at DefaultedAnimate (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:575192:9)
    at NonInjectedAnimate
    at NonInjectedDrawer (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:594452:9)
    at observerComponent (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:240471:16)
    at observerComponent (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:240471:16)
    at ObserverComponent (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:240519:23)
    at ErrorBoundary (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:594915:9)
    at observerComponent (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:240471:16)
    at ThemeProvider (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:124521:24)
    at Router (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:457461:30)
```

```
Error stack:

TypeError: factory.create is not a function
    at createTextBuffer (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:337307:20)
    at new TextModel (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:337396:44)
    at ModelServiceImpl._createModelData (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:345393:23)
    at ModelServiceImpl.createModel (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:345434:30)
    at doCreateModel (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:393337:25)
    at createTextModel (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:393331:12)
    at Object.createModel (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:402199:12)
    at NonInjectedMonacoEditor.get model (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:609424:35)
    at ComputedValue.computeValue_ (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:243170:33)
    at ComputedValue.get (http://69ac451ab302dcba22efd2afcc334be9.localhost:49581/build/Lens.js?efb54d12584c4a7a3002:243091:28)
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: ...
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: knime
    user: kubernetes-admin
  name: demo
current-context: demo
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: ...
    client-key-data: ...
```

**Comment by Nokel81** [comment] 2022-08-15 12:54
Duplicate of https://github.com/lensapp/lens/issues/5645

**Closed as not planned by Nokel81** 2022-08-15 12:54 UTC
Labels: bug
