### ISSUE TITLE
adding helm custom repo does nothing

### ISSUE THREAD

**Issue by anubisg1** [kontena/lens#6629] opened 2022-11-22 21:01 UTC
**Describe the bug**
adding helm custom repo does nothing

**To Reproduce**
1.Go to settings --> kubernetes
2. add custom repo
3. click on add
4. nothing happens and logs shows nothing 

**Expected behavior**
a repo should be added

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 6.2.1
- OS: windows 10
- Installation method windows installer 

**Logs:**
nothing is generated when clicking on add repo
log entries about helm are generated when adding a repo pulled from the drop down list instead

**Comment by kyleli666** [comment] 2022-11-24 11:31
same here.

**Comment by Nokel81** [comment] 2022-11-28 13:50
Can you post a short video of what you are trying to do? Does the modal not show up?

**Comment by Nokel81** [comment] 2022-11-28 13:51
Is this a duplicate of https://github.com/lensapp/lens/issues/6566?

**Comment by anubisg1** [comment] 2022-11-28 13:53
pressing "add" (step 3) does absolutely nothing, no logs, no errors, nothing what so ever 

![image](https://user-images.githubusercontent.com/4518931/204294541-e2478cd7-42d8-4c67-b4aa-664d5c9635d7.png)

**Comment by Aykelith** [comment] 2022-11-30 21:03
I can confirm here too.

Lens: 2022.11.251411-latest
Extension API: 6.2.3
Electron: 19.1.7
Chrome: 102.0.5005.167
Node: 16.14.2

**Closed as completed** 2022-12-02 12:53 UTC
Labels: bug, area/helm
