### ISSUE TITLE
Container File Explorer

### ISSUE THREAD

**Issue by numeralnathan** [kontena/lens#5730] opened 2022-06-25 17:42 UTC
**What would you like to be added**:

I would like the ability to explorer the files in a container.  I would like to be able to double-click on a file and open it on my desktop.  If I edit and save the file, please copy the file back.  I would like to be able to Ctrl + C on a file and copy it to my desktop.  I would like to be able to drag and drop a file from the container to my desktop or from my desktop to the container.

**Why is this needed**:

This will allow me to check on the contents of files very quickly.  It will allow me to edit files and put them back.  It will allow me to copy heap dumps and other diagnostic files to my laptop for further work.  It will allow me to upload tools and scripts to do further diagnostics.

**Environment you are Lens application on:**

- Kubernetes distribution: Unknown
- Desktop OS: Windows 11

**Comment by Nokel81** [comment] 2022-06-27 13:14
Duplicate of https://github.com/lensapp/lens/issues/2362

**Closed as not planned by Nokel81** 2022-06-27 13:14 UTC
Labels: enhancement
