### ISSUE TITLE
Lens Metrics. Update interval granularity

### ISSUE THREAD

**Issue by AndreiPaulau** [kontena/lens#3853] opened 2021-09-21 12:16 UTC
**What would you like to be added**:
It would be great to have a possibility to manage update metrics update interval for the resources.
For example, I have a pod with memory leak identified. Currently metrics graph is updated every minute and I wasn't able to find settings to update this interval. So the leak is happening very fast within a 30 sec, so I won't be able to identify the spike.
Yeah, I know that the purpose of lens is slightly different, but it always great to have swiss knife in your pocket.
Still it doesn't look so complex from the glance to implement dropdown window with 5/10/30/60 sec update interval options.

**Why is this needed**:
Great to have for debug and better resource visibility.

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
1.17.14
- Desktop OS: <the OS Lens app runs on in your case>
Win10

Many thanks

**Comment by Nokel81** [comment] 2021-09-27 12:54
Duplicate of https://github.com/lensapp/lens/issues/3577

**Closed as completed by Nokel81** 2021-09-27 12:54 UTC
Labels: enhancement
