### ISSUE TITLE
createTerminalTab with node fails to open a node shell request

### ISSUE THREAD

**Issue by alebcay** [kontena/lens#7091] opened 2023-02-02 04:17 UTC
**Describe the bug**
When an extension calls `createTerminalTab` with a `node` set, a terminal tab is opened but stuck `Connecting...`. The `node-shell` pod is created and can be `kubectl exec`'ed into to obtain a shell, but the original terminal tab is stuck with `Connecting...`.

**To Reproduce**
1. Install an extension that calls `createTerminalTab` with a `node`, such as [alebcay/openlens-node-pod-menu](https://github.com/alebcay/openlens-node-pod-menu).
2. Perform any action that calls `createTerminalTab` with a `node`. A terminal tab should be opened and display `Connecting...`.
3. The actual node shell will not be loaded and instead will be stuck on `Connecting...`.

**Expected behavior**
The connection to the node shell pod should be established properly in the original node shell tab as it was in previous versions.

**Screenshots**

![Screen Shot 2023-02-01 at 11 12 09 PM](https://user-images.githubusercontent.com/3536482/216230269-3b8df446-6057-4aa7-826b-71ad8573a7fc.png)

![Screen Shot 2023-02-01 at 11 12 18 PM](https://user-images.githubusercontent.com/3536482/216230284-9760ec5e-12b6-4e28-ae08-f9564a004b16.png)

**Environment (please complete the following information):**
- Lens Version: 6.4.0-beta.10 and 6.4.0-alpha.3
- OS: macOS
- Installation method (e.g. snap or AppImage in Linux): Built from source

**Logs:**

```
[81393:0201/230454.105199:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -207
info:    ┏ [CLUSTER]: refresh +5s
info:    ┃ [1] {
info:    ┃ [2]   id: '4bbbaf0671fe16f535b16ee54a970150',
info:    ┃ [3]   name: 'minikube',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [UNIX-SHELL-ENV]: running against /usr/local/bin/zsh +1s
info:    ┃ [1] {
info:    ┃ [2]   command: ` '/Volumes/Storage/Developer/lens/packages/open-lens/dist/mac/OpenLens.app/Contents/MacOS/OpenLens' -p '"cbbd4af5c1644dd1a43a12d3d1b15085" + JSON.stringify(process.env) + "cbbd4af5c1644dd1a43a12d3d1b15085"'`,
info:    ┃ [3]   shellArgs: [ '-l', '-i' ]
info:    ┗ [4] }
error:   ┏ [SHELL-SESSION]: failed to open a node shell request to https://127.0.0.1:55820/api-kube/api/v1/nodes/minikube failed, reason: Hostname/IP does not match certificate's altnames: Host: 4bbbaf0671fe16f535b16ee54a970150.localhost. is not in the cert's altnames: DNS:*.lens.app, DNS:lens.app, DNS:localhost, IP Address:127.0.0.1 +20ms
error:   ┃ [ 1] d: request to https://127.0.0.1:55820/api-kube/api/v1/nodes/minikube failed, reason: Hostname/IP does not match certificate's altnames: Host: 4bbbaf0671fe16f535b16ee54a970150.localhost. is not in the cert's altnames: DNS:*.lens.app, DNS:lens.app, DNS:localhost, IP Address:127.0.0.1
error:   ┃ [ 2]     at ClientRequest.<anonymous> (/Volumes/Storage/Developer/lens/packages/open-lens/dist/mac/OpenLens.app/Contents/Resources/app.asar/node_modules/@k8slens/core/node_modules/@k8slens/node-fetch/dist/index.js:2:81899)
error:   ┃ [ 3]     at ClientRequest.emit (node:events:526:28)
error:   ┃ [ 4]     at ClientRequest.emit (node:domain:475:12)
error:   ┃ [ 5]     at TLSSocket.socketErrorListener (node:_http_client:442:9)
error:   ┃ [ 6]     at TLSSocket.emit (node:events:526:28)
error:   ┃ [ 7]     at TLSSocket.emit (node:domain:475:12)
error:   ┃ [ 8]     at emitErrorNT (node:internal/streams/destroy:157:8)
error:   ┃ [ 9]     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
error:   ┃ [10]     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
error:   ┃ [11] {
error:   ┃ [12]   type: 'system',
error:   ┃ [13]   errno: 'ERR_TLS_CERT_ALTNAME_INVALID',
error:   ┃ [14]   code: 'ERR_TLS_CERT_ALTNAME_INVALID',
error:   ┃ [15]   erroredSysCall: undefined
error:   ┗ [16] }
```

**Kubeconfig:**

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redacted
    server: https://127.0.0.1:6443
  name: default
- cluster:
    certificate-authority: /Users/caleb/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 31 Jan 2023 16:34:22 EST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: cluster_info
    server: https://localhost:56111/
  name: minikube
contexts:
- context:
    cluster: default
    user: default
  name: default
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 31 Jan 2023 16:34:22 EST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: redacted
    client-key-data: redacted
- name: minikube
  user:
    client-certificate: /Users/caleb/.minikube/profiles/minikube/client.crt
    client-key: /Users/caleb/.minikube/profiles/minikube/client.key
```

**Additional context**
The issue was observed with minikube (where the kubeconfig and screenshot above are from). Same issue was observed with GKE.

**Comment by Nokel81** [comment] 2023-02-13 13:22
Closing as duplicate of https://github.com/lensapp/lens/issues/7138, even though this is newer. Thanks for the report.

**Closed as completed by Nokel81** 2023-02-13 13:22 UTC
Labels: bug
