### ISSUE TITLE
App crash at /deployments

### ISSUE THREAD

**Issue by homer6** [kontena/lens#5493] opened 2022-05-28 17:32 UTC
**Describe the bug**
App crash at /deployments

**To Reproduce**
Not sure. However, I was installing the bitnami/jupyterhub helm chart in lens (browsing deployments after successfully upgrading the helm chart actually). I don't think it's related to that, but that's what I was doing.

**Expected behavior**
No crash.

**Screenshots**
<img width="1332" alt="2022-05-28_10h29_22" src="https://user-images.githubusercontent.com/371329/170836368-87607910-fb33-40bd-81e9-1a1fbd7059e4.png">

**Environment (please complete the following information):**
- Lens Version: <img width="274" alt="2022-05-28_10h30_21" src="https://user-images.githubusercontent.com/371329/170836409-de8fd948-f8c9-4103-86cf-154d75547527.png">

- Windows 11: Edition	Windows 11 Pro
Version	21H2
Installed on	‎2022-‎01-‎26
OS build	22000.675
Experience	Windows Feature Experience Pack 1000.22000.675.0

- Installation method (e.g. snap or AppImage in Linux): Windows installer (upgraded lens)

**Comment by ksa-real** [comment] 2022-05-28 21:56
Likely a duplicate of #5490

**Comment by Nokel81** [comment] 2022-05-30 13:25
Fixed by https://github.com/lensapp/lens/pull/5479, new patch release will be released today including that fix.

**Closed as not planned by Nokel81** 2022-05-30 13:25 UTC
Labels: bug
