### ISSUE TITLE
Custom Resource Events

### ISSUE THREAD

**Issue by pintonunes** [kontena/lens#4937] opened 2022-02-27 11:28 UTC
**What would you like to be added**:
Custom Resource Events in the object details pane

**Why is this needed**:
Lots of controllers generate events for their CRs. Today we can only see them in the global events pane.
Would be awesome if we can see then in the CR details pane filtered by the object like we have for k8s standard objects.

![image](https://user-images.githubusercontent.com/37883272/155880562-60629848-dcd8-4e41-bd61-0c7e73cebf30.png)

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS]
- Desktop OS: Windows

**Comment by Nokel81** [comment] 2022-02-28 14:22
Duplicate of https://github.com/lensapp/lens/issues/3770

**Closed as completed by Nokel81** 2022-02-28 14:22 UTC
Labels: enhancement
