### ISSUE TITLE
Allow column width size to be changed

### ISSUE THREAD

**Issue by PJChamley** [kontena/lens#7123] opened 2023-02-08 10:00 UTC
The ability to manually change the column width in all sub sections, user experience should be consistent across the application and this feature added to all section that have columns.

Some columns are not auto sized correctly or I may want to see more of a column as not all data show.

As an example the node column under Workloads - Pods 
for me typically columns like node are not displaying the last 2 or 3 characters. It would be nice to be able to extent this column's width to make the content visible at the expense of other columns or for a horizontal scrollbar to become visible. 

Using Lens 2023.1
- Desktop OS: Windows 11

**Comment by Nokel81** [comment] 2023-02-13 13:53
Duplicate of #601

**Closed as completed by Nokel81** 2023-02-13 13:53 UTC
Labels: enhancement
