### ISSUE TITLE
5.3.0-latest.20211125.2 does not display windows on Windows 10

### ISSUE THREAD

**Issue by AndrewSav** [kontena/lens#4473] opened 2021-11-30 23:46 UTC
**Describe the bug**
When I run the lens executable no windows come up and no tray icon. I can see 4 lens.exe processes in the task manager.

**To Reproduce**
Can only reproduce on my laptop. On the laptop it happens 100% of the time. Start the app, the window does not show up. I also tried to reboot a few times and to uninstall / reinstall a few times. No joy.

**Expected behavior**
I expect to see the main Lens window and the tray icon.

**Screenshots**
This is the screenshot from ProcessExplorer showing Lens processes:

![2021-12-01_12-42-03](https://user-images.githubusercontent.com/27190911/144145648-bbb4671d-ab9b-4be2-9239-02b6eb128f4a.png)

**Environment (please complete the following information):**
- Lens Version: 5.3.0-latest.20211125.2
- OS: Windows 10
- Installation method:  Lens Setup 5.3.0-latest.20211125.2.exe

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register succeeded ✅ +2ms
info:    ▪ [APP-PATHS]: initializing +0ms
```

**Kubeconfig:**

 I have removed the entire `.kube` folder for the test, It is _not_ kubeconfig.

**Additional context**
Worked fine before that latest update.
To clarify, since there a [comment](https://github.com/lensapp/lens/issues/4473#issuecomment-983331381) talking about something else. Lens does not show _any_ UI at all. There is no window and no tray icon displayed, not even the main Lens window.

**Comment by AndrewSav** [comment] 2021-11-30 23:51
Similar report in comments: https://github.com/lensapp/lens/issues/4430#issuecomment-981433238

**Comment by TIANQIEND** [comment] 2021-12-01 06:30
![image](https://user-images.githubusercontent.com/34571669/144185295-acf4c440-c570-4843-b7ef-7f28a9042438.png)

I meet the same problem on win10,like picture
version:5.3.0-latest.20211130.1

**Comment by AndrewSav** [comment] 2021-12-01 07:22
Just to clarify, the comment about is **not** the same problem. It is unrelated for the issue reported. On the comment above there is a screenshot of Lens window displayed, in the case reported there is no window shows up. 

@TIANQIEND I suggest you open a separate issue for the problem _you_ are having because this is not it.

**Comment by DavidCsaki** [comment] 2021-12-01 14:04
Having same problem as originally reported with Lens Setup 5.3.1-latest.20211130.1.exe

**Comment by jim-docker** [comment] 2021-12-01 14:12
Did you try moving or removing the `%APPDATA%\Lens\` folder? (Not sure if it is removed as part of uninstalling Lens)

**Comment by DavidCsaki** [comment] 2021-12-01 14:28
Problem still occurs for me after removing %APPDATA%\Lens\ folder and re-installing.

**Comment by jim-docker** [comment] 2021-12-01 16:20
@DavidCsaki, @AndrewSav, 
- anything else in the logs (https://docs.k8slens.dev/main/faq/#where-can-i-find-application-logs)?
- did you install for current user or all users?
- anything custom about your Windows 10 setup (proxy, network settings/apps, display language, ...)?

**Comment by DavidCsaki** [comment] 2021-12-01 16:31
[lens.log](https://github.com/lensapp/lens/files/7635581/lens.log)
same configuration was working fine for v5.2
but when Lens dialog popped up saying 5.3 was available, and I clicked to install & never got it working again

**Comment by jim-docker** [comment] 2021-12-01 18:48
I've tried to reproduce on two windows machine with no luck so far so I'm just looking for what might be different

**Comment by DavidCsaki** [comment] 2021-12-01 19:19
In my case:
Windows 10 Enterprise
Version 10.0.18363

**Comment by andrewsav-bt** [comment] 2021-12-01 22:21
> @DavidCsaki, @AndrewSav,
> 
> * anything else in the logs (https://docs.k8slens.dev/main/faq/#where-can-i-find-application-logs)?

Same as David's

> * did you install for current user or all users?

Current user

> * anything custom about your Windows 10 setup (proxy, network settings/apps, display language, ...)?

It's hard to pin-point. No proxy, this is a dev machine so have boat load of network adapters: vmware, virtualbox, hyper-v, corporate VPN you name it, display language is English, although I have a russian keyboard and default russian locale. None of this has changed since previous release which worked fine.

**Comment by andrewsav-bt** [comment] 2021-12-01 22:23
> Did you try moving or removing the `%APPDATA%\Lens\` folder? (Not sure if it is removed as part of uninstalling Lens)

Yes. No impact.

**Comment by AndrewSav** [comment] 2021-12-02 02:05
> @DavidCsaki, @AndrewSav,
> 
> * anything else in the logs (https://docs.k8slens.dev/main/faq/#where-can-i-find-application-logs)?

Same as David's

> * did you install for current user or all users?

Current user

> * anything custom about your Windows 10 setup (proxy, network settings/apps, display language, ...)?

It's hard to pin-point. No proxy, this is a dev machine so have boat load of network adapters: vmware, virtualbox, hyper-v, corporate VPN you name it, display language is English, although I have a russian keyboard and default russian locale. None of this has changed since previous release which worked fine.

**Comment by AndrewSav** [comment] 2021-12-02 02:05
> Did you try moving or removing the `%APPDATA%\Lens\` folder? (Not sure if it is removed as part of uninstalling Lens)

Yes. No impact.

**Comment by jim-docker** [comment] 2021-12-02 17:26
Can someone see if there are more logs in debug mode? You need to set `DEBUG=1` and run lens from a terminal. In powershell you can do:  
```
$env:DEBUG = 1
cd $HOME\AppData\Local\Programs\Lens\
.\Lens.exe
```
(assuming you installed Lens for the current user)
Logs will appear in the terminal

More debug logs will be in 5.3.3 when it comes out, to try to narrow the root of the problem down.

**Comment by DavidCsaki** [comment] 2021-12-02 17:59
[lens-debug.log](https://github.com/lensapp/lens/files/7644143/lens-debug.log)

**Comment by DavidCsaki** [comment] 2021-12-02 18:09
when I create the %HOME%\Music directory, I still have the problem of GUI not appearing, but only below in terminal:


info:    Γû¬ ≡ƒôƒ Setting Lens as protocol client for lens:// +0ms
info:    Γû¬ ≡ƒôƒ Protocol client register succeeded Γ£à +3ms
info:    Γû¬ [APP-PATHS]: initializing +2ms

**Comment by AndrewSav** [comment] 2021-12-02 19:55
@DavidCsaki creating the Music directory actually worked for me _if I kill all the hang lens processes first_. After creating the music directory I see the Lens window and it starts up normally. I had similar logs to yours, complaining about Music before that. @jim-docker  Can you explain why Lens is suddenly interested in my Music and fails if I do not have any? Is it "analytics"?

**Comment by DavidCsaki** [comment] 2021-12-02 20:15
@AndrewSav thanks for the tip, I must have missed to kill all procs, now Lens starts normally.
I already have a music player, don't need/want Lens playing music ;-)

**Comment by DavidCsaki** [comment] 2021-12-02 20:28
@jim-docker Seem bad behavior if there is no 'videos' directory. Was some malware introduced?
[lens-debug.log](https://github.com/lensapp/lens/files/7644887/lens-debug.log)

**Comment by jim-docker** [comment] 2021-12-02 20:29
Oops. We recently added code to populate all the app paths for the app framework we use (Electron). I think it was done just for completeness but Lens only relies on a few, appData mostly. Thanks for finding the root of the problem @AndrewSav and @DavidCsaki !

**Closed as completed** 2021-12-03 01:52 UTC
Labels: bug
