### ISSUE TITLE
Ingress view doesn't show individual ingresses

### ISSUE THREAD

**Issue by despick** [kontena/lens#4574] opened 2021-12-15 10:50 UTC
**Describe the bug**
When i go to the ingress view and select an ingress, the side panel doesn't open. The ingress is marked as selected. Clicking on the 3 dots next to the ingress entry doesn't do anything.

**To Reproduce**
1. Go to 'Ingress'
2. Click on any ingress entry
3. Nothing happens, usually a side panel with more info would open from the right side. Also clicking on the 3 dots would not do anything.

**Expected behavior**
Open the side right panel when you click on an ingress entry.

**Screenshots**
The ingress view before clicking on an ingress <img width="1043" alt="not selected" src="https://user-images.githubusercontent.com/17095540/146172818-b561ab4a-df42-44f3-b7f0-0d4277be349c.png">
The ingress view after selecting an ingress <img width="1026" alt="selected" src="https://user-images.githubusercontent.com/17095540/146172834-c6d908fa-c03b-4a2a-b9f8-dbf26829bdef.png">

**Environment (please complete the following information):**
- Lens Version: 5.3.2-latest.20211201.1
- OS: OSX Bigsur 11.6.1
- Installation method (e.g. snap or AppImage in Linux): dmg

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
This behaviour started with lens 5.3

**Comment by Nokel81** [comment] 2021-12-15 13:48
Duplicate of https://github.com/lensapp/lens/issues/4531 and is fixed in 5.3.3 which is already released.

**Closed as completed by Nokel81** 2021-12-15 13:48 UTC
Labels: bug
