### ISSUE TITLE
After last update lens Crashes repeatedly. 

### ISSUE THREAD

**Issue by mzubairsaleem** [kontena/lens#4490] opened 2021-12-02 20:51 UTC

**Comment by Rickaro** [comment] 2021-12-03 08:07
Hi, I've experience "hungs" after last update too.

Lens version: version: '5.3.2-latest.20211201.1' 
Platform: Windows 10 x64
Shell: Powershell

Steps to reproduce:
Open lens, connect to cluster, start pod shell, terminate pod (for example delete it), shell will be dicsonnected (command terminated with exit code 137), try to close shell tab. After some time 3-5 sec - lens window hungs, and not responding.

Lens log:
```
# Start shell, close shell when pod running
info:    ▪ [SHELL-SESSION]: PTY for fd56e830795d7a393601eea3f9ffa1e0:7e6d27b4-6542-4510-8b97-eb1614234c8f is started with PID=16468 +15s
info:    ┏ [SHELL-SESSION]: websocket for fd56e830795d7a393601eea3f9ffa1e0:7e6d27b4-6542-4510-8b97-eb1614234c8f closed with code=NoStatusReceived(1005) +5s
info:    ▪ [SHELL-SESSION]: Killing shell process (pid=16468) for fd56e830795d7a393601eea3f9ffa1e0:7e6d27b4-6542-4510-8b97-eb1614234c8f +2ms
info:    ▪ [SHELL-SESSION]: shell has exited for fd56e830795d7a393601eea3f9ffa1e0:7e6d27b4-6542-4510-8b97-eb1614234c8f closed with exitcode=0 +277ms

# Start shell, terminate pod, close shell
info:    ▪ [SHELL-SESSION]: PTY for fd56e830795d7a393601eea3f9ffa1e0:de2edb86-6d4d-42f3-8de0-7f7097ae5464 is started with PID=28684 +3s
info:    ┏ [SHELL-SESSION]: websocket for fd56e830795d7a393601eea3f9ffa1e0:de2edb86-6d4d-42f3-8de0-7f7097ae5464 closed with code=NoStatusReceived(1005) +18s
info:    ▪ [SHELL-SESSION]: Killing shell process (pid=28684) for fd56e830795d7a393601eea3f9ffa1e0:de2edb86-6d4d-42f3-8de0-7f7097ae5464 +1ms
```

In DevTools no any clue, except error, when shell tab closed. But this error happend in "normal process" and when "hung happend"

```
Uncaught TypeError: Cannot read property 'url' of null
    at TerminalApi._onClose (websocket-api.ts:201)
    at TerminalApi._onClose (terminal-api.ts:208)
    at WebSocket.<anonymous> (websocket-api.ts:127)
```

**Comment by george2asenov** [comment] 2021-12-03 08:09
same issue here on two PC's

**Comment by lucacalcaterra** [comment] 2021-12-03 15:56
same issue here

**Comment by TheHakky** [comment] 2021-12-06 09:39
Same issue. When I open and close a terminal session in Lens, it crushes after a couple of seconds.

Lens version: version: 5.3.2-latest.20211201.1
Platform: Windows 10 x64

**Comment by AndrasSandor** [comment] 2021-12-07 04:38
got the same issue

**Comment by akashsharma95** [comment] 2021-12-07 06:48
it crashes most of the time

**Comment by Nokel81** [comment] 2021-12-08 16:46
Duplicate of https://github.com/lensapp/lens/issues/4430

**Closed as completed by Nokel81** 2021-12-08 16:46 UTC
Labels: bug, blocker, p0, area/terminal

**Comment by tiglymigly** [comment] 2021-12-09 07:57
same here. 5.3.2-latest.20211201.1, win10

**Comment by mzubairsaleem** [comment] 2021-12-09 11:49
APP Crashes again. 

Logs:

```
**Component stack:**


    at ClusterStatus (http://localhost:61604/build/chunks/7.js:2784:9)
    at div
    at ClusterView (http://localhost:61604/build/chunks/7.js:3078:9)
    at Route (http://localhost:61604/build/Lens.js:79389:29)
    at Switch (http://localhost:61604/build/Lens.js:79555:29)
    at main
    at div
    at ClusterManager (http://localhost:61604/build/chunks/7.js:4821:38)
    at Route (http://localhost:61604/build/Lens.js:79389:29)
    at Switch (http://localhost:61604/build/Lens.js:79555:29)
    at ErrorBoundary (http://localhost:61604/build/Lens.js:237949:9)
    at Router (http://localhost:61604/build/Lens.js:79054:30)
    at RootFrame (http://localhost:61604/build/chunks/7.js:5681:9)
    at ThemeProvider (http://localhost:61604/build/Lens.js:609758:24)
```

```
**Error stack:**

TypeError: Cannot read property 'getName' of undefined
    at ClusterStatus.render (http://localhost:61604/build/chunks/7.js:2874:71)
    at allowStateChanges (http://localhost:61604/build/Lens.js:2571:12)
    at http://localhost:61604/build/Lens.js:11008:59
    at trackDerivedFunction (http://localhost:61604/build/Lens.js:3120:18)
    at Reaction.track (http://localhost:61604/build/Lens.js:3649:18)
    at ClusterStatus.reactiveRender [as render] (http://localhost:61604/build/Lens.js:11006:14)
    at qi (http://localhost:61604/build/Lens.js:556376:188)
    at pi (http://localhost:61604/build/Lens.js:556375:173)
    at ck (http://localhost:61604/build/Lens.js:556458:427)
    at bk (http://localhost:61604/build/Lens.js:556439:347)
    at ak (http://localhost:61604/build/Lens.js:556439:278)
    at Tj (http://localhost:61604/build/Lens.js:556439:138)
    at Lj (http://localhost:61604/build/Lens.js:556432:163)
    at http://localhost:61604/build/Lens.js:556312:115
    at exports.unstable_runWithPriority (http://localhost:61604/build/Lens.js:556523:343)
    at gg (http://localhost:61604/build/Lens.js:556311:325)
    at jg (http://localhost:61604/build/Lens.js:556312:61)
    at ig (http://localhost:61604/build/Lens.js:556311:428)
    at Wj (http://localhost:61604/build/Lens.js:556433:190)
    at reactionScheduler (http://localhost:61604/build/Lens.js:3776:12)
    at http://localhost:61604/build/Lens.js:3777:14
    at Bh (D:\KubernetesLense\resources\extensions\lenscloud-lens-extension\dist\renderer.js:699:141185)
    at reactionScheduler (http://localhost:61604/build/Lens.js:3776:12)
    at runReactions (http://localhost:61604/build/Lens.js:3745:3)
    at endBatch (http://localhost:61604/build/Lens.js:3413:5)
    at _endAction (http://localhost:61604/build/Lens.js:2560:3)
    at executeAction (http://localhost:61604/build/Lens.js:2513:5)
    at catalog_entity_registry_CatalogEntityRegistry.updateItems (http://localhost:61604/build/Lens.js:2492:12)
    at EventEmitter.<anonymous> (http://localhost:61604/build/Lens.js:69064:18)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)
```
