### ISSUE TITLE
v6.3.0 connected but nothing shown because of kubectl not downloaded

### ISSUE THREAD

**Issue by odedonato** [kontena/lens#6820] opened 2022-12-22 10:50 UTC
**Describe the bug**
Connected to K8s cluster but nothing shown because kubectl was not downloaded, see logs

**To Reproduce**
1. Build
2. Connect to k8s
3. Nothing shown on window

**Expected behavior**
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/3715824/209115933-c57914f6-fa92-44fc-bfe1-82232b5f71c8.png">

**Screenshots**
<img width="996" alt="image" src="https://user-images.githubusercontent.com/3715824/209116200-ad3d2ccf-1b05-432c-ba1c-fe9b3938f126.png">

**Environment (please complete the following information):**
- Lens Version: 6.3.0
- OS: MacOs 13.1 on M2 (arm64)
- Installation method (e.g. snap or AppImage in Linux): Compiled

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    ▪ Downloading kubectl 1.17.17 from https://storage.googleapis.com/kubernetes-release/release/v1.17.17/bin/darwin/arm64/kubectl to /Users/omar/Library/Application Support/OpenLens/binaries/kubectl/1.17.17/kubectl +2s
error:   ┏ [KUBECTL]: failed to download kubectl Response code 404 (Not Found) +219ms
error:   ┃ [ 1] HTTPError: Response code 404 (Not Found)
error:   ┃ [ 2]     at Request._onResponseBase (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/got/dist/source/core/index.js:913:31)
error:   ┃ [ 3]     at Request._onResponse (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/got/dist/source/core/index.js:948:24)
error:   ┃ [ 4]     at ClientRequest.<anonymous> (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/got/dist/source/core/index.js:962:23)
error:   ┃ [ 5]     at Object.onceWrapper (node:events:646:26)
error:   ┃ [ 6]     at ClientRequest.emit (node:events:538:35)
error:   ┃ [ 7]     at ClientRequest.emit (node:domain:475:12)
error:   ┃ [ 8]     at origin.emit (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
error:   ┃ [ 9]     at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
error:   ┃ [10]     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
error:   ┃ [11]     at TLSSocket.socketOnData (node:_http_client:482:22)
error:   ┃ [12] {
error:   ┃ [13]   name: 'HTTPError',
error:   ┃ [14]   code: 'ERR_NON_2XX_3XX_RESPONSE',
error:   ┃ [15]   timings: {
error:   ┃ [16]     start: 1671705954668,
error:   ┃ [17]     socket: 1671705954668,
error:   ┃ [18]     lookup: 1671705954669,
error:   ┃ [19]     connect: 1671705954691,
error:   ┃ [20]     secureConnect: 1671705954732,
error:   ┃ [21]     upload: 1671705954732,
error:   ┃ [22]     response: 1671705954874,
error:   ┃ [23]     end: 1671705954876,
error:   ┃ [24]     error: undefined,
error:   ┃ [25]     abort: 1671705954878,
error:   ┃ [26]     phases: { wait: 0, dns: 1, tcp: 22, tls: 41, request: 0, firstByte: 142, download: 2, total: 210 }
error:   ┃ [27]   }
error:   ┗ [28] }
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
Not a kubeconfig problem, it works with older version.
```

**Additional context**
Nothing.

**Comment by gaspo53** [comment] 2022-12-22 12:30
Kind of related here, cluster info goes blak, and then after a refresh (cmd + r) it works. Then, there's no Execute icon to enter a pod nor tail logs:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/2250227/209134802-487a0047-3cb1-4771-bd85-0e2ffe796a9e.png">

**Comment by odedonato** [comment] 2022-12-22 13:04
> Kind of related here, cluster info goes blak, and then after a refresh (cmd + r) it works. Then, there's no Execute icon to enter a pod nor tail logs: <img alt="image" width="738" src="https://user-images.githubusercontent.com/2250227/209134802-487a0047-3cb1-4771-bd85-0e2ffe796a9e.png">

I can confirm! (tried now cmd +r)

**Comment by nisc-acooper** [comment] 2022-12-22 18:08
We are seeing the same issue,  we do not have the kubectl download error

![image](https://user-images.githubusercontent.com/1648514/209198360-fec5fa5a-8567-491d-8091-089e37f48ca8.png)

macOS 12.6 Intel

**Comment by msa0311** [comment] 2022-12-23 08:11
duplicate of #6824

**Closed as completed by msa0311** 2022-12-23 08:11 UTC
Labels: bug
