### ISSUE TITLE
Allow more than 12 items in the hot bar

### ISSUE THREAD

**Issue by matti** [kontena/lens#6263] opened 2022-09-16 10:06 UTC
<img width="2002" alt="image" src="https://user-images.githubusercontent.com/3893/190615051-5f8e1a9c-a82f-4172-9bf2-4c50722b4f3f.png">

**Comment by Nokel81** [comment] 2022-10-03 13:15
Duplicate of #5400

**Closed as not planned by Nokel81** 2022-10-03 13:15 UTC
Labels: enhancement
