### ISSUE TITLE
Pods filter by Status

### ISSUE THREAD

**Issue by josepowera** [kontena/lens#4202] opened 2021-10-31 15:06 UTC
**What would you like to be added**:
On Workloads->Pods allow to filter by status.

That would help user to filter any pending or "non running" pods.

**Why is this needed**:
We run > 200 pods and finding anything not running takes time and is error prone.

**Environment you are Lens application on:**
non enviorment specific
- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- k3s
- Desktop OS: <the OS Lens app runs on in your case>
windows

**Comment by Nokel81** [comment] 2021-11-01 14:04
FYI the search field does search the status message on the pods.

**Comment by Nokel81** [comment] 2021-11-05 18:31
Closing as duplicate of https://github.com/lensapp/lens/issues/2069

**Closed as completed by Nokel81** 2021-11-05 18:31 UTC
Labels: enhancement
