### ISSUE TITLE
Option to fold managed fields by default.

### ISSUE THREAD

**Issue by ksa-real** [kontena/lens#4892] opened 2022-02-16 23:29 UTC
**What would you like to be added**:
When editing most of K8s objects with Lens edit feature, it shows `metadata.managedFields` field. It creates a lot of visual noice. There are some other fields that are rarely needed, e.g. `ownerReference`, but they are less of the issue. The ask is to allow folding `managedFields` automatically on edit. This may be controlled via preferences. 

It was a long-time annoying issue and recently I saw ArgoCD project which appeared to contains this option.

**Why is this needed**:
Looking into managed fields is a very rare operation in everyday life.

**Environment you are Lens application on:**
- Self-hosted Kubernetes. This is irrelevant though.
- MacOS.

**Comment by Nokel81** [comment] 2022-02-17 13:18
Duplicate of #2765

**Closed as completed by Nokel81** 2022-02-17 13:18 UTC
Labels: enhancement
