### ISSUE TITLE
App crash at /cluster 

### ISSUE THREAD

**Issue by clidrobalo** [kontena/lens#4195] opened 2021-10-29 16:38 UTC
**Describe the bug**
Receiving "App crash at /cluster", "Cannot read property 'namespace' of undefined"

**To Reproduce**
1. Open the cluster
![image](https://user-images.githubusercontent.com/29333444/139472002-da21b09d-31ef-4ceb-a9fe-2a7eb922f96d.png)

**Expected behavior**
Expected to show cluster details

**Screenshots**
![image](https://user-images.githubusercontent.com/29333444/139471196-9e481638-0a41-41b3-8086-33de79a2cb36.png)

**Environment:**
- Lens Version: [5.1.3-latest]
- OS: [Windows]

**Logs:**
```
TypeError: Cannot read property 'namespace' of undefined
    at pods_api_Pod.getNs (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:511980:30)
    at pods_api_Pod.getOwnerRefs (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:512011:32)
    at http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:541299:30
    at http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:7000:49
    at http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:6964:25
    at trackDerivedFunction (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:1881:18)
    at Reaction.track (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:2409:18)
    at useObserver (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:6962:14)
    at http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:7000:16
    at Ch (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:450238:137)
    at li (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:450261:154)
    at ki (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:450259:169)
    at ck (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:450355:157)
    at bk (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:450331:347)
    at ak (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:450331:278)
    at Tj (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:450331:138)
    at Lj (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:450324:163)
    at http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:450204:115
    at exports.unstable_runWithPriority (http://dcfe1e83de2c026973d143ca1fd82bd7.localhost:57199/build/Lens.js:450415:343)
```

**Comment by Nokel81** [comment] 2021-10-29 18:28
Duplicate of #3543

**Closed as completed by Nokel81** 2021-10-29 18:28 UTC
Labels: bug
